export type BlogPost = {
  id: string
  slug: string
  title: string
  excerpt: string
  category: string
  author: string
  publishedAt: string
  readTime: string
  thumbnail: string
  content: {
    attention: string[]
    interest: string[]
    desire: string[]
    action: string[]
  }
  seo: {
    metaTitle: string
    metaDescription: string
    keywords: string[]
  }
}

export const BLOG_POSTS: BlogPost[] = [
  {
    id: '1',
    slug: '5-pratimai-sedmenu-formavimui-namuose',
    title: '5 Efektyvūs Pratimai Sėdmenų Formavimui Namuose (Be Inventoriaus)',
    excerpt: 'Sužinok, kaip per 4 savaites pasiekti apvalesnes ir tvirtas sėdmenis treniruodamasi namuose - be brangaus inventoriaus.',
    category: 'Treniruotės',
    author: 'Renata Marcinkutė',
    publishedAt: '2025-10-15',
    readTime: '8 min',
    thumbnail: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&h=600&fit=crop&q=80',
    content: {
      attention: [
        'Ar svajoji apie apvalesnes ir tvirtas sėdmenis, bet neturi laiko eiti į sporto klubą? Tu ne viena! Daugelis moterų susiduria su ta pačia problema - noras formuoti sėdmenis yra, bet kasdienybė neleidžia skirti kelių valandų treniruotėms salėje.',
        'Gera žinia: tau nereikia brangaus inventoriaus ar sporto klubo abonamento. Šie 5 pratimai, kuriuos galima atlikti namuose, yra pagrįsti biomechanikos principais ir tikrai veikia sėdmenų raumenis.',
  'Per 4 savaites reguliariai treniruodamasi (3-4 kartus per savaitę) pastebėsi tikrus pokyčius – sėdmenys taps tvirtesni, apvalesni ir pakilę.'
      ],
      interest: [
  '**1. PRISĖDIMAI (Squats)** - Karališkasis pratimas sėdmenims. Stovėk kojomis per pečius, kojų pirštus lengvai išversk į išorę. Lėtai leiskis žemyn, tarsi sėstum ant kėdės, keliai neturi eiti už kojų pirštų. Grįžk į pradinę poziciją spausdama per kulnus. 3 serijos po 15-20 kartojimų.',
  '**Kodėl veikia:** Squats aktyvuoja visas tris sėdmenų raumenų grupes (didysis, vidutinis ir mažasis sėdmenų raumenys) ir papildomai stiprina šlaunų keturgalvius.',
  '**2. IŠPUOLIAI (Lunges)** - Ženk žingsnį į priekį viena koja, leiskis žemyn, kol abu keliai sulinks 90 laipsnių kampu. Grįžk spausdama per priekinės kojos kulną. Keisk kojas. 3 serijos po 12 kartojimų kiekvienai kojai.',
        '**Kodėl veikia:** Išpuoliai ne tik formuoja sėdmenis, bet ir gerina pusiausvyrą bei koordinaciją. Jie izoliuoja kiekvieną koją atskirai, todėl abi pusės vystosi vienodai.',
        '**3. TILTAS (Glute Bridge)** - Gulėk ant nugaros, kelius sulenk, pėdos plokščiai ant grindų, rankos šonuose. Kelk klubus aukštyn, spausk sėdmenis viršuje 2 sekundes. Lėtai grįžk. 3 serijos po 20 kartojimų.',
        '**Kodėl veikia:** Tai vienas geriausių pratimų didžiajam sėdmenų raumeniui izoliuoti. Tiltas taip pat stiprina apatinę nugarą ir pagerina laikyseną.',
        '**4. VIENAKOJIS TILTAS** - Kaip įprastas tiltas, bet viena koja ištiesinta į viršų. Tai padvigubina krūvį ant vienos pusės. 3 serijos po 10-12 kartojimų kiekvienai kojai.',
        '**Kodėl veikia:** Didina intensyvumą be papildomo svorio. Puikus pratimas stuburo stabilizatoriams.',
  '**5. GAISRINIAI HIDRANTAI (Fire Hydrants)** - Ant keturių (rankos ir keliai), viena koja sulenkta 90 laipsnių kampu ir kelk į šoną, tarsi šuo prie hidranto. 3 serijos po 15 kartojimų kiekvienai kojai.',
        '**Kodėl veikia:** Šis pratimas tikslingai dirba su vidutiniu sėdmenų raumeniu, kuris atsakingas už sėdmenų apvalumą šonuose ir klubų stabilumą.'
      ],
      desire: [
        '**Kaip sudėlioti į programą?** Atlikite šiuos pratimus 3-4 kartus per savaitę. Pradėk nuo nurodyto kartojimų skaičiaus ir kas savaitę didink po 2-3 kartojimus arba pridėk papildomą seriją.',
        '**Pro patarimas:** Norint maksimalių rezultatų, tarp serijų ilsėkis 60-90 sekundžių. Tarp treniruočių dienų daryk bent 1 dieną poilsio - raumenys auga poilsio metu!',
        '**Mityba = 70% rezultato.** Kad sėdmenys augtų, reikia baltymų! Siekis: 1.6-2g baltymų kg kūno svorio. Geriausi šaltiniai: vištiena, žuvis, kiaušiniai, graikiškas jogurtas, tofu.',
        '**Tikri rezultatai iš mano bendruomenės:** "Per 6 savaites pastebėjau, kad mano džinsai pradėjo kitaip sėdėti - sėdmenys pasidarė tvirčiau ir apvaliau! Darau šiuos pratimus kas antrą dieną." - Laura, 34 m.',
        '**Svarbu:** Pirmąsias 2 savaites gali būti raumenų skausmas (DOMS). Tai normalu! Bet jei jaučiate aštrų skausmą treniruotės metu - sustokite ir pasitikrinkite techniką.',
        '**Papildomi bonusai:** Šie pratimai ne tik formuoja sėdmenis - jie taip pat stiprina kojas, gerina laikyseną, mažina apatinės nugaros skausmą ir padidina bendrą kūno jėgą.'
      ],
      action: [
        '**Pradėk šiandien!** Nereikia laukti pirmadienio ar kito mėnesio. Šie 5 pratimai užtruks tik 20 minučių. Įdėk šią programą į savo kalendorių dabar - pirmadienis, trečiadienis, penktadienis.',
        '**Nori greičiau pasiekti tikslą?** Mūsų "Sėdmenų formavimo" programa suteikia:',
        '• Pilną 8 savaičių treniruočių planą su progresija',
        '• Video instrukcijas kiekvienam pratimui',
        '• Mitybos gaires raumenų augimui',
        '• Prieigą prie Renata Ladies bendruomenės palaikymui',
        '**[Sužinok daugiau apie programą →](/programos/sedmenu-treniruote-video)**',
        'Ar nori individualizuoto plano? Rezervuok nemokamą 15 min konsultaciją su manimi ir aptarsime tavo tikslus!',
        '**[Rezervuoti konsultaciją →](/konsultacijos)**',
        '**P.S.** Fotografuok savo progresą! Nusifotografuok dabar ir po 4 savaičių - pamatysi skirtumą. Žymėk mane Instagram @renataladies - norėčiau pamatyti tavo rezultatus! 💪✨'
      ]
    },
    seo: {
      metaTitle: '5 Pratimai Sėdmenų Formavimui Namuose (2025) | Renata Ladies',
      metaDescription: 'Sužinok, kaip per 4 savaites pasiekti apvalesnes sėdmenis treniruodamasi namuose be inventoriaus. Ekspertės patarimai ir tikra programa.',
      keywords: ['sėdmenų pratimai', 'pratimai namuose', 'kaip formuoti sėdmenis', 'treniruotės moterims', 'squats', 'glute bridge', 'lunges']
    }
  },
  {
    id: '2',
    slug: 'kaip-numesti-5-kg-per-menesi-sveikai',
    title: 'Kaip Numesti 5 kg Per Mėnesį Sveikai ir Be Jo-Jo Efekto',
    excerpt: 'Realistiškas ir sveikas planas kaip numesti 5 kg per 30 dienų. Patvirtinta mokslo ir realių moterų rezultatų.',
    category: 'Mityba',
    author: 'Renata Marcinkutė',
    publishedAt: '2025-10-10',
    readTime: '10 min',
    thumbnail: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800&h=600&fit=crop&q=80',
    content: {
      attention: [
        'Tikėjimas: "Norint numesti svorio, reikia badauti ir skaičiuoti kiekvieną kaloriją." Tiesa: Numesti 5 kg per mėnesį galima valgant skaniai ir sočiai, be nuolatinio alkio jausmo.',
        'Problema, su kuria susiduria 90% moterų: pradedi dietą, pirmas 2 savaites eina puikiai, bet paskui - žlugimas. Grįžti prie senų įpročių ir svoris grįžta atgal (Jo-Jo efektas).',
        'Šis straipsnis parašytas moterims, kurios nori realių rezultatų be kraštutinumų. Jokių "stebuklingo arbatos", jokių "detox sulčių", tik patvirtinti mokslo būdai ir strategijos, kurios veikia ilgalaikėje perspektyvoje.'
      ],
      interest: [
        '**Matematika yra paprasta:** Norint numesti 1 kg riebalų, reikia sukurti 7700 kalorijų deficitą. Norint numesti 5 kg per 30 dienų = 38,500 kalorijų deficitas = 1,283 kalorijų deficitas per dieną.',
        '**Bet čia svarbu suprasti:** Nebadauk! 1,200-1,300 kalorijų deficitas turėtų ateiti iš dviejų šaltinių:',
        '• 600-700 kalorijų deficitas iš mitybos (valgyk mažiau nei degi)',
        '• 500-600 kalorijų sudegink per fizinį aktyvumą (treniruotės + NEAT)',
        '**Kas yra NEAT?** Non-Exercise Activity Thermogenesis - kalorijos, kurias degi ne per treniruotes: vaikščiojimas, laiptais lipimas, namų darbai, žaidimas su vaikais. NEAT gali sudeginti 300-800 kalorijų per dieną!',
        '**4 Pagrindiniai Ramsčiai:**',
        '**1. MITYBA (70% rezultato)**',
        '• Baltymai: 1.8-2.2g/kg kūno svorio (saugo raumenis, ilgai sotina)',
        '• Skaiduliniai angliavandeniai: daržovės, vaisiai, pilno grūdo produktai',
  '• Sveiki riebalai: avokadas, riešutai, alyvuogių aliejus (hormonų gamybai!)',
  '• Vanduo: 2-3L per dieną (dažnai alkio jausmas yra tik troškulys)',
        '**2. JĖGOS TRENIRUOTĖS (3-4x/savaitę)**',
        'Kodėl svarbu? Jėgos treniruotės saugo raumenis, kai meti svorį. Be jų, gali prarasti ne tik riebalus, bet ir raumenis - tada metabolizmas sulėtės ir svoris grįš greičiau.',
        '**3. KARDIO (2-3x/savaitę)**',
        '30-45 min vidutinio intensyvumo (greitas ėjimas, dviračio treniruoklis, plaukimas). Sudegina ~300-400 kalorijų per sesiją.',
        '**4. MIEGAS IR STRESO VALDYMAS**',
        'Mažiau nei 7h miego = padidėjęs kortizolis = stubrus svoris + alkio pojūtis. Miegas = slapta ginklas!'
      ],
      desire: [
        '**Kaip atrodo ideali savaitė:**',
        '**Pirmadienis:** Jėgos treniruotė (visa kūno) + 10k žingsnių',
        '**Antradienis:** 30 min kardio + 8k žingsnių',
  '**Trečiadienis:** Jėgos treniruotė (apatinė dalis) + 10k žingsnių',
        '**Ketvirtadienis:** Aktyvus poilsis (yoga, tempimas) + 8k žingsnių',
        '**Penktadienis:** Jėgos treniruotė (viršutinė dalis) + 10k žingsnių',
        '**Šeštadienis:** 45 min kardio + linksma veikla (šokiai, krepšinis)',
        '**Sekmadienis:** Poilsio diena (bet vis tiek juda! - pasivaikščiojimas parke)',
        '**Mitybos pavyzdys (1,500 kcal dienai):**',
        '🍳 **Pusryčiai (400 kcal):** Omletas iš 3 kiaušinių su špinatais ir pomidorais + 1 griežinėlis pilno grūdo duonos',
        '🥗 **Pietūs (500 kcal):** 150g keptos vištienos krūtinėlės + kvinoja + didelis daržovių salotų dubuo su alyvuogių aliejumi',
        '🍎 **Užkandis (200 kcal):** Graikiškas jogurtas su uogomis ir šaukštu migdolų',
        '🍲 **Vakarienė (400 kcal):** Kepta lašiša su brokoliais ir saldžiomis bulvėmis',
        '**Tikri rezultatai:**',
        '"Per 4 savaites numečiau 6 kg! Ir svarbiausia - nesijuto, kad būčiau dietoje. Valgiau skanų maistą ir turėjau energijos treniruotėms." - Ieva, 35 m.',
        '"Pirmą kartą gyvenime svorio metimas neatrodė kaip kančia. Išmokau maitintis sveikai ir tai tapo gyvenimo būdu." - Laura, 28 m.'
      ],
      action: [
        '**Tavo 7 dienų iššūkis - PRADĖK DABAR:**',
        '**1 diena:** Apskaičiuok savo kalorijas (naudok TDEE kalkuliatorių) ir nustatyk 500-700 kcal deficitą',
        '**2 diena:** Suplanuok 3 pagrindinius valgius ir 2 užkandžius savaitei',
        '**3 diena:** Pirk produktus pagal sąrašą (nesirink alkanas!)',
        '**4 diena:** Atlik pirmą jėgos treniruotę (gali būti ir 20 min!)',
  '**5 diena:** Nueik 10 000 žingsnių',
        '**6 diena:** Paruošk 3 valgius iš anksto sekančiai dienai',
  '**7 diena:** Nusisverk ir nusifotografuok - tai tavo atspirties taškas!',
        '**Nori greičiau pasiekti tikslą?**',
        'Mūsų "Svorio Metimo" programa suteikia:',
        '• Personalizuotą mitybos planą pagal tavo svorį ir tikslus',
        '• 30 dienų treniruočių programą namams ar salei',
        '• Receptų knygą su >50 sveikų ir skanių receptų',
        '• Savaitinį check-in su manimi ir grįžtamąjį ryšį',
        '**[Sužinok apie programą →](/mitybos-planai)**',
        'Ar nori individualizuoto plano? Rezervuok nemokamą 15 min konsultaciją su manimi!',
        '**[Rezervuoti konsultaciją →](/konsultacijos)**',
        '**P.S.** Įsimink: Svoris - tai tik vienas rodiklis. Fotografuok save, matuok apimtis, stebėk, kaip jaučiasi drabužiai. Raumenys sveria daugiau nei riebalai, bet atrodo daug geriau! 📸💪'
      ]
    },
    seo: {
      metaTitle: 'Kaip Numesti 5 kg Per Mėnesį Sveikai (2025) | Renata Ladies',
      metaDescription: 'Patvirtinta strategija kaip numesti 5kg per 30 dienų be Jo-Jo efekto. Mityba + treniruotės + tikri rezultatai.',
      keywords: ['kaip numesti svorio', 'svorio metimas', 'dieta moterims', 'kaip numesti 5 kg', 'sveika mityba', 'kalorijų deficitas']
    }
  },
  {
    id: '3',
    slug: 'idealus-pusryciu-planas-moterims',
    title: 'Idealūs Pusryčiai Aktyviai Moteriai: 7 Receptai Savaitei',
    excerpt: 'Greitai paruošiami, sotūs ir sveiki pusryčiai, kurie duos energijos visai dienai. Su baltymais, skaidulomis ir sveikais riebalais.',
    category: 'Receptai',
    author: 'Renata Marcinkutė',
    publishedAt: '2025-10-05',
    readTime: '12 min',
    thumbnail: 'https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?w=800&h=600&fit=crop&q=80',
    content: {
      attention: [
  'Kiek kartų esi girdėjusi "pusryčiai – svarbiausias dienos valgis"? Bet realiame gyvenime – skubėjimas, vaikų ruošimas, darbas... ir pusryčiai tampa kava su sausainiu arba išvis praleidžiami.',
  'Statistika šokiruojanti: 60% moterų praleidžia pusryčius arba valgo tik kavą. Pasekmė? 11 val. jau mirtinas alkis, potraukis saldumynams, energijos trūkumas.',
        'Gera žinia: pusryčiai GALI būti greiti, skanūs ir maistingi. Šie 7 receptai užims ne daugiau nei 10 minučių ruošti, bet duos energijos iki pietų!'
      ],
      interest: [
        '**Kas sudaro idealius pusryčius?**',
        '✅ **Baltymai:** 25-30g (sočiai, saugo raumenis, stabilizuoja cukrų)',
        '✅ **Sudėtingi angliavandeniai:** energija visam rytui',
        '✅ **Sveiki riebalai:** hormonų gamybai, sočiumui',
  '✅ **Skaidulos:** virškinimui, ilgalaikiam sotumui',
        '',
        '**PIRMADIENIS - Baltyminis Omletas Dubenyje**',
        '**Ingredientai:** 3 kiaušiniai, 50g špinatų, 50g pomidorų, 30g feta sūrio, alyvuogių aliejus',
        '**Paruošimas (7 min):** Išplak kiaušinius su druska/pipirais. Keptuvėje ant alyvuogių aliejaus apkepk špinatą ir pomidorus 2 min. Supilk kiaušinius, viršų barstyk feta. Kepk 3-4 min ant mažos ugnies.',
        '**Maistingumas:** 350 kcal | 28g baltymų | 8g angliavandenių | 22g riebalų',
        '**Kodėl veikia:** Aukštas baltymų kiekis išlaiko sotumą iki pietų. Feta suteikia druskingumo, o daržovės - skaidulų.',
        '',
        '**ANTRADIENIS - Graikiškas Jogurtas su Granola ir Uogomis**',
        '**Ingredientai:** 200g graikiškas jogurtas (10% rieb.), 40g granola, 80g mišrių uogų, 1 š. š. medaus, 10g chia sėklų',
        '**Paruošimas (3 min):** Į dubenį supilk jogurtą, viršų uogas, granola, chia ir medų. Pamaišyk.',
        '**Maistingumas:** 420 kcal | 24g baltymų | 48g angliavandenių | 14g riebalų',
        '**Pro patarimas:** Paruošk granola sekmadienį didelį kiekį - užteks visai savaitei!',
        '',
        '**TREČIADIENIS - Avokado Tostas su Kiaušiniu**',
        '**Ingredientai:** 2 griežinėliai pilno grūdo duonos, 1 avokadas, 2 kiaušiniai, citrinos sultys, čili dribsniai, druska',
  '**Paruošimas (8 min):** Pakepk duoną. Sutrink avokadą su citrina ir druska. Patepk ant duonos. Iškepk kiaušinius (sunny side up arba scrambled). Dėk ant avokado, barstyk čili.',
        '**Maistingumas:** 480 kcal | 22g baltymų | 38g angliavandenių | 26g riebalų',
        '**Kodėl myliu:** Sveiki riebalai iš avokado palaiko hormonų balansą. Idealus po intensyvios ryto treniruotės!',
        '',
        '**KETVIRTADIENIS - Baltyminis Smoothie Bowl**',
  '**Ingredientai:** 1 šaldytas bananas, 150g mišrių uogų, 30g baltymų miltelių (vanilės), 100ml migdolų pieno, užpilai: kokoso drožlės, chia, granola, kivis',
  '**Paruošimas (5 min):** Sumaišyk blenderyje bananą, uogas, baltymus ir pieną iki tirštos masės. Supilk į dubenį. Išpuošk toppings.',
        '**Maistingumas:** 380 kcal | 32g baltymų | 45g angliavandenių | 8g riebalų',
  '**Kada valgyti:** Idealus po rytinės treniruotės – greiti angliavandeniai atstatymui + baltymai raumenims!',
        '',
        '**PENKTADIENIS - Bananų Blynai su Žemės Riešutų Sviestu**',
        '**Ingredientai:** 2 bananai, 3 kiaušiniai, 40g avižų dribsnių, 1 a. š. kepimo miltelių, cinamonas, žemės riešutų sviestas',
  '**Paruošimas (10 min):** Sutrink bananus šakute, sumaišyk su kiaušiniais. Pridėk avižas, kepimo miltelius, cinamoną. Kepk ant keptuvės kaip blynus (po 2 min kiekvieną pusę). Patiek su ž.r. sviestu.',
        '**Maistingumas:** 440 kcal | 24g baltymų | 52g angliavandenių | 16g riebalų',
  '**Vaikams:** Vaikai šiuos blynus dievina! 😄 Puikus būdas "paslėpti" baltymus ir skaidulas.',
        '',
        '**ŠEŠTADIENIS - Lengva Quinoa Košė**',
        '**Ingredientai:** 60g kvinoja, 200ml kokoso pieno, 1 š. š. medaus, cinamonas, toppings: migdolai, uogos, kokoso drožlės',
  '**Paruošimas (15 min):** Išvirk kvinoją pagal instrukcijas. Supilk kokoso pieną, medų, cinamoną. Virink 5 min, kol sutirštės. Patiek su toppings.',
        '**Maistingumas:** 410 kcal | 12g baltymų | 58g angliavandenių | 14g riebalų',
        '**Kada:** Puikus šeštadienio rytas, kai yra daugiau laiko. Šilta, jaukūs, paguodžianti košė.',
        '',
        '**SEKMADIENIS - Lašiša su Kreminiu Sūriu ir Bagel**',
        '**Ingredientai:** 1 pilno grūdo bagel, 60g kreminio sūrio, 80g rūkytos lašišos, agurkas, raudonieji svogūnai, krapai',
  '**Paruošimas (5 min):** Pakepk arba pašildyk bagel. Patepk kreminiu sūriu. Dėk lašišą, plonus agurko griežinėlius, svogūnus, krapus.',
  '**Maistingumas:** 450 kcal | 28g baltymų | 42g angliavandenių | 18g riebalų',
  '**Kodėl sekmadieniui:** Jaučiasi šiek tiek "fancy" – neskubūs, džiaugsmingi pusryčiai. Omega-3 iš lašišos = anti-inflammatory.'
      ],
      desire: [
        '**Meal Prep Patarimai:**',
        '• **Sekmadienį:** Iškepk granola, išvirk 6-8 kiaušinius, supjaustyk daržoves',
        '• **Laikyk šaldytuve:** Jau paruošti daržovių mišiniai omletams',
  '• **Šaldiklyje:** Šaldyti bananai smoothie, paruoštos blynų porcijos',
        '• **Sausame inde:** Avižų dribsniai, chia sėklos, riešutai',
        '',
        '**Biudžeto Patarimai:**',
  'Šie pusryčiai kainuoja vidutiniškai €2-3 per porciją. Brangiausi - lašiša ir avokadas (savaitgaliams). Pigiausi - blynai ir jogurtas.',
        '',
        '**Dažniausi Klausimai:**',
        '**"O jei nesu alkana ryte?"** Pradėk nuo mažesnės porcijos arba smoothie. Kūnas pripras prie pusryčių per 2 savaites.',
        '**"Kiek laiko prieš treniruotę valgyti?"** Jei treniruojiesi ryte - valgyk 30-60 min prieš. Jei po treniruotės - per 30 min po.',
        '**"Ar galiu praleisti pusryčius jei darau intermittent fasting?"** Taip! Bet šie receptai puikūs ir pietums/vakarienei. 😊'
      ],
      action: [
        '**7 Dienų Pusryčių Iššūkis - PRADĖK RYTOJ:**',
        'Įsipareigok savaitę valgyti šiuos pusryčius pagal planą. Stebėk kaip jaučiasi:',
        '✓ Energijos lygis 11 val.',
        '✓ Saldumynų troškimas',
        '✓ Bendras nuotaikos lygis',
        '✓ Miego kokybė',
        '',
        'Lažiuosi, kad po savaitės nenorėsi grįžti prie "kavos su sausainiu" režimo!',
        '',
        '**Nori daugiau receptų?**',
        'Mūsų "Mitybos Planas" programoje gausi:',
        '• 90+ sveikų receptų (pusryčiai, pietūs, vakarienė, užkandžiai)',
        '• Savaitiniai shopping lists',
        '• Meal prep guide',
        '• Kalorių ir makroelementų apskaičiavimai kiekvienam receptui',
        '**[Peržiūrėk mitybos planus →](/mitybos-planai)**',
        '',
        'Ar nori personalizuoto mitybos plano pagal tavo tikslus ir maisto pageidavimus?',
        '**[Rezervuoti konsultaciją →](/konsultacijos)**',
        '',
        '**P.S.** Pasidalink su drauge, kuri visada skundžiasi "neturiu laiko pusryčiams"! Išspausdink šį puslapį ir prikabink ant šaldytuvo - turėsi visos savaitės planą! 🍳☕'
      ]
    },
    seo: {
      metaTitle: '7 Sveikų Pusryčių Receptai Savaitei (2025) | Renata Ladies',
      metaDescription: 'Greiti, skanūs ir maistingi pusryčiai aktyviai moteriai. 7 receptai su baltymais savaitei - kiekvienas per 10 min!',
      keywords: ['sveiki pusryčiai', 'pusryčių receptai', 'baltymų pusryčiai', 'greiti pusryčiai', 'pusryčiai moterims', 'sveika mityba']
    }
  },
  {
    id: '4',
    slug: 'kaip-atsigauti-po-gimdymo',
    title: 'Sauga ir Efektyvus Sugrįžimas Į Formą Po Gimdymo',
    excerpt: 'Ekspertės gidas kaip saugiai pradėti treniruotis po gimdymo, stiprinti pilvo raumenis ir atgauti energiją. Su 6 savaičių planu.',
    category: 'Gyvenimo būdas',
    author: 'Renata Marcinkutė',
    publishedAt: '2025-09-28',
    readTime: '15 min',
    thumbnail: 'https://images.unsplash.com/photo-1555252333-9f8e92e65df9?w=800&h=600&fit=crop&q=80',
    content: {
      attention: [
  'Dabar esi namuose su naujagimiu, žiūri į veidrodį ir galvoji "kada aš vėl jausiuosi kaip AŠ?" Tu ne viena. 85% moterų po gimdymo jaučia slegiamą spaudimą grįžti į "priešgimdyminę formą" per kelias savaites.',
  'Bet štai tiesa, kurią dažnai nutyli: tavo kūnas praleido 9 mėnesius augindamas žmogų. Jam reikia laiko, kantrybės ir TINKAMO požiūrio atsigauti.',
        'Šis straipsnis parašytas siekiant padėti tau saugiai ir efektyviai sugrįžti į aktyvų gyvenimą po gimdymo - be spaudimo, be nerealių lūkesčių, su meile savo kūnui.'
      ],
      interest: [
        '**SVARBU: Visuomet konsultuokis su gydytoju prieš pradedant bet kokią treniruotę po gimdymo!**',
        '',
        '**Kada galima pradėti treniruotis?**',
  '• **Natūralus gimdymas:** Paprastai po 6 savaičių (po gydytojo patikrinimo)',
        '• **Cezario pjūvis:** Dažniausiai 8-12 savaičių (reikia gydytojo leidimo)',
        '• **Komplikacijų atveju:** Gali užtrukti ilgiau - klausyk savo gydytojo!',
        '',
        '**Ženklai, kad dar NESI pasiruošusi:**',
        '❌ Kraujavimas vis dar stiprus',
        '❌ Aštrūs skausmai pilvo arba dubens srityje',
        '❌ Šlapimo nelaikymas (daugiau nei lengvas nutekėjimas čiaudint)',
        '❌ Pilvo raumenų diastas > 2-3 pirštų pločio',
        '',
  '**FAZĖ 1: Savaitės 1-6 po gimdymo (Atsigavimas)**',
  'Tikslas: Atstatymas, ne formavimas. Ramūs tempimo pratimai, kvėpavimo technikoms, dubens dugno raumenų stiprinimas.',
        '',
        '**Kas yra dubens dugno raumenys ir kodėl jie svarbūs?**',
  'Dubens dugno raumenys palaiko šlapimo pūslę, žarnyną ir gimdą. Nėštumas ir gimdymas juos nusilpnina. Jei nestiprinsi – gali pasireikšti šlapimo nelaikymas, pilvo išsipūtimas, nugaros skausmas.',
        '',
        '**Kegel pratimai (darykite KASDIEN):**',
        '• Įtemk dubens dugno raumenis (tarsi sustabdytum šlapimo srovę)',
        '• Laikyk 5 sekundes',
        '• Atpalaiduok 5 sekundes',
        '• Kartok 10 kartų, 3 kartus per dieną',
        '',
        '**Gilus pilvo kvėpavimas:**',
        'Gulėk ant nugaros, kelius sulenk. Įkvėpk giliai nosimi - pilvas turėtų pakilti. Iškvėpk per burną, švelniai įtraukdama pilvo raumenis. 5 min kasdien.',
        '',
  '**FAZĖ 2: Savaitės 6-12 (Švelnūs judesiai)**',
  'Tikslas: Laipsniškas kardio įjungimas, švelnūs jėgos pratimai.',
        '',
        '**Leistini pratimai:**',
        '✅ Greitas ėjimas (pradėk nuo 15 min, didink iki 30-45 min)',
        '✅ Yoga (postpartum yoga klasės)',
        '✅ Plaukimas (jei gimdymo žaizdos užgijusios)',
  '✅ Stacionarus dviratis (lengvu pasipriešinimu)',
        '✅ TRX pratimai (modifikuoti)',
        '',
  '**Pratimai dubens dugno stiprinimui:**',
  '**1. Tiltas:** Gulėk ant nugaros, keliai sulenkti. Kelk klubus, spausk dubens dugną. Laikyk 5 sek. 10 kartų.',
        '**2. Cat-Cow:** Ant keturių. Įkvėpk - nugara žemyn, galva aukštyn. Iškvėpk - nugara aukštyn, galva žemyn. 10 kartų.',
  '**3. Sieninis sėdėjimas:** Nugarą prispaudusi prie sienos, leiskis žemyn tarsi sėstum. Laikyk 20-30 sek.',
        '',
  '**FAZĖ 3: Mėnesiai 3-6 (Progresija)**',
        'Tikslas: Laipsniškai didinti intensyvumą, jėgos treniruotės, kardio.',
        '',
        '**Dabar gali:**',
        '✅ Lengvos jėgos treniruotės (pradėk su kūno svoriu, paskui lengvais svarmenimis)',
        '✅ Intervalinė treniruotė (HIIT modifikuota)',
        '✅ Bėgimas (jei dubens dugnas stiprus ir nėra nutekėjimo)',
        '✅ Grupinės klasės (postpartum pritaikytos)',
        '',
        '**6 Savaičių "Mama Strong" Programa:**',
        '**Savaitės 1-2:** 3x/sav - 20 min greitas ėjimas + dubens dugno pratimai',
        '**Savaitės 3-4:** 3x/sav - 25 min kardio + kūno svorio jėga (squats, lunges, plank modifikuotas)',
        '**Savaitės 5-6:** 4x/sav - 30 min kardio + pilnas kūnas jėga su lengvais svarmenimis'
      ],
      desire: [
  '**Mityba po gimdymo:**',
        '**Jei maitini krūtimi:** +500 kcal per dieną (virš normalaus poreikio)',
  '**Baltymai:** 1,8-2 g/kg – raumenų atsigavimui',
  '**Vanduo:** 3-4 L per dieną (ypač jei maitini krūtimi)',
  '**Geležis:** Daugelis moterų po gimdymo turi geležies deficitą – valgyk raudoną mėsą, špinatus, pupeles',
        '',
        '**SVARBU: Dabar NE laikas dietai! Tavo kūnas atsikovoja ir (galbūt) maitina kūdikį. Fokusas - maistingumas, ne kalorijų apribojimas.**',
        '',
        '**Diastas Abdominis (Pilvo raumenų išsiskyrimas):**',
        'Kas tai? Pilvo raumenys po nėštumo gali išsiskirti viduryje. Tai normalu, bet reikia tinkamai stiprinti.',
        '',
        '**Kaip patikrinti:**',
  'Gulėk ant nugaros, kelius sulenk. Kelk galvą tarsi darytum crunch. Pirštais pačiupinėk tarp raumenų ties bamba. Jei tarpas > 2-3 pirštų – turime diastą.',
        '',
        '**Pratimai DIASTUI (DARYKITE):**',
        '✅ Transverse abdominal breathing',
        '✅ Pelvic tilts',
        '✅ Modified plank (ant kelių)',
        '✅ Dead bug (modifikuotas)',
        '',
        '**Pratimai VENGTI su diastu:**',
        '❌ Tradiciniai crunches',
        '❌ Sit-ups',
        '❌ Pilnas plank ant kojų (pradžioje)',
        '❌ Sunkūs svoriai (pradžioje)',
        '',
        '**Tikros Mamos Dalina Patirtį:**',
  '"Po cezario pjūvio išlaukiau 12 savaičių. Pradėjau nuo 10 min ėjimo. Dabar (8 mėnesiai po gimdymo) treniruojuosi 4x/sav. ir jaučiuosi stipresnė nei prieš nėštumą!" - Ieva, 32 m.',
  '"Turėjau 3 pirštų diastą. Dirbau su kineziterapeute 3 mėnesius. Dabar diastas sumažėjo iki 1 piršto ir galiu daryti normalius pilvo pratimus!" - Laura, 29 m.',
        '',
  '**Kada kreiptis į specialistus:**',
  '• Diastas > 3 pirštų ir neužsitraukia per 3 mėnesius',
        '• Nuolatinis šlapimo nelaikymas',
        '• Skausmas per lytinius santykius',
        '• Jaučiamas "spaudimas" dubenyje',
        '**Kreipkis į dubens dugno fizioterapeutų - jos ekspertės šioje srityje!**'
      ],
      action: [
        '**Tavo Postpartum Action Plan:**',
        '',
  '**☑ Savaitės 1-6:**',
  '• Gauk gydytojo leidimą pradėti pratimus',
  '• Daryk Kegel pratimus kasdien (nustatyk priminimą telefone!)',
        '• 10 min gilus kvėpavimas kasdien',
  '• Miegok, kai kūdikis miega (atsigavimas > treniruotės!)',
        '',
  '**☑ Savaitės 6-12:**',
  '• Pasitikrink diastą (arba pas gydytoją/kineziterapeutę)',
  '• Pradėk 15 min ėjimo programą',
  '• Tęsk dubens dugno stiprinimą',
  '• Sudaryk realistišką treniruočių grafiką (pvz., 3×20 min/savaitę)',
        '',
  '**☑ Mėnesiai 3-6:**',
  '• Įtrauk jėgos treniruotes (pradėk nuo kūno svorio)',
  '• Laipsniškai didink kardio intensyvumą',
  '• Stebėk progresą – fotografuok, rašyk dienoraštį',
        '',
        '**Nori personalizuoto postpartum plano?**',
        'Mūsų "Postpartum Recovery" programa sukurta specialiai mamoms:',
        '• 12 savaičių treniruočių programa (saugi po gimdymo)',
        '• Dubens dugno stiprinimo pratimai',
        '• Diastas abdominis gydymo protokolas',
        '• Mitybos planas maitinančioms/nemaitinančioms',
        '• Savaitinė parama ir check-ins',
  '**[Sužinok apie Postpartum programą →](/programos/postpartum-recovery)**',
        '',
  'Nori individualizuotos konsultacijos dėl postpartum recovery?',
  '**[Rezervuoti konsultaciją →](/konsultacijos)**',
        '',
  '**P.S. Atmink:** Tavo kūnas padarė STEBUKLŲ – jis išaugino žmogų! Būk kantri, mylinti ir neskubėk. "Snapback" kultūra yra toksiška. Tavo tikslas – sveikata ir jėga, ne "pre-baby body". Tu esi nuostabi! 💪👶💕'
      ]
    },
    seo: {
      metaTitle: 'Kaip Saugiai Treniruotis Po Gimdymo (2025) | Renata Ladies',
      metaDescription: 'Pilnas gidas po gimdymo: kada pradėti, kokie pratimai saugūs, kaip stiprinti pilvo ir dubens dugno raumenis. 6 savaičių planas.',
      keywords: ['treniruotės po gimdymo', 'postpartum workout', 'diastas abdominis', 'dubens dugno pratimai', 'po gimdymo forma', 'mama fitness']
    }
  },
  {
    id: '5',
    slug: 'motyvacija-kaip-nepasiduoti',
    title: 'Kaip Išlikti Motyvuotai Kai Viskas Atrodo Neįmanoma',
    excerpt: 'Tikri psichologijos būdai kaip išlaikyti motyvaciją ilgalaikėje perspektyvoje. Be "toxic positivity", tik kas tikrai veikia.',
    category: 'Motyvacija',
    author: 'Renata Marcinkutė',
    publishedAt: '2025-09-20',
    readTime: '10 min',
    thumbnail: 'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=800&h=600&fit=crop&q=80',
    content: {
      attention: [
  'Pirmadienio rytas. Skamba žadintuvas 6:00. Tu turėtum atsikelti ir eiti treniruotis. Bet... lova šilta, darbo diena bus sunki, vakar valgei picos... "Gal rytoj. Rytoj tikrai pradėsiu."',
        'Taip atrodo motyvacijos žūtis. Ne dramatiška, ne staiga. Tiesiog... tyliai iššluoji. Vieną praleidžiamą treniruotę, vieną "netrūksta vienos dienos", vieną "nuo pirmadienio" vienu metu.',
        'Bet štai tiesa: motyvacija yra JAUSMAS. Jausmai keičiasi. Tai, ko tau tikrai reikia, yra ne motyvacija - tai DISCIPLINA ir SISTEMOS.'
      ],
      interest: [
        '**Motyvacijos Mitas:**',
        'Daugelis tiki, kad sėkmingos moterys, kurios treniruojasi 5x/savaitę ir valgo sveikai, visada yra "motyvuotos". Melas!',
        '',
        'Tiesa: Jos turi SISTEMAS, kurios veikia net kai motyvacijos nėra.',
        '',
  '**Moksliniai faktai apie motyvaciją:**',
        '• Vidutinė motyvacijos trukmė naujai pradėjus - **72 valandos** (3 dienos!)',
        '• 80% naujametinių tikslų žlugsta iki **vasario** (6 savaitės)',
        '• Įpročio formavimui reikia **66 dienų** (ne 21, kaip dažnai sakoma)',
        '',
        '**7 Strategijos Išlaikyti "Motyvaciją" (Discipliną):**',
        '',
  '**1. KEISK TAPATYBĘ, NE TIK TIKSLĄ**',
        'Blogai: "Noriu numesti 10kg"',
        'Gerai: "Aš esu žmogus, kuris rūpinasi savo sveikata"',
        '',
        'Kodėl veikia? Identity-pagrįsti sprendimai yra stipresni. "Sveiki žmonės" neturi "nuspręsti" ar eiti treniruotis - tai tiesiog kas jie yra.',
        '',
  '**2. SUMAŽINK SPRENDIMŲ NUOVARGĮ**',
  'Kiekvienas sprendimas eikvoja valios jėgą. Kai 18:00 po darbo klausi savęs "ar šiandien treniruosiuosi?" – atsakymas dažniausiai bus "ne".',
        '',
        'Sprendimas: **Iš anksto nuspręsk.** Pavyzdys:',
        '• Treniruotės: Pirmad/Treč/Penk 18:00 (automatiškai)',
  '• Drabužiai: paruošti vakare prieš',
        '• Maistas: meal prep sekmadienį',
        '',
        '**3. APLINKOS DIZAINAS (Environment Design)**',
  'Padaryk LENGVA daryti tai, ką nori daryti. Sunku – tai, ko nenori.',
        '',
        'Pavyzdžiai:',
        '✅ Sportiniai bateliai šalia lovos (pirmą matai atsikėlusi)',
  '✅ Vandens buteliukas ant naktinio staliuko',
        '✅ Sveikų užkandžių ofise (riešutai, vaisiai)',
        '❌ Saldumynai namų viršutinėje lentynoje (sunku pasiekti)',
  '❌ Pašalink telefoną nuo lovos (nesėdėsi Instagram 1 val.)',
        '',
  '**4. IMPLEMENTACIJOS INTENCIJA (If-Then Plans)**',
        'Tyrimas rodo: žmonės su "jei-tada" planais 2-3x labiau laikosi savo įsipareigojimų.',
        '',
        'Formulė: "Jei [situacija], tada [veiksmas]"',
        '',
        'Pavyzdžiai:',
  '• Jei atsikelsiu ir neturėsiu motyvacijos, tada vis tiek apsirengsiu sportiniais.',
        '• Jei draugės pasiūlys pietums fast food, tada pasakysiu "ne, turiu meal prep".',
        '• Jei praleisiu ryto treniruotę, tada darysiu 20 min vakare.',
        '',
        '**5. 5 MINUČIŲ TAISYKLĖ**',
  'Kai neturi motyvacijos: pasižadėk sau tik **5 minutes**. Po 5 min gali sustoti.',
        '',
  'Kas nutinka? 90% atvejų tęsi. Pradėti yra sunkiausia dalis. Bet kai jau apsirengi sporto drabužiais ir pajudi – smegenys "įsijungia".',
        '',
        '**6. PROGRESS TRACKING (Progreso Sekimas)**',
        'Kas yra išmatuota, yra padaryta. Stebėk ir švęsk mažus laimėjimus.',
        '',
        'Būdai sekti:',
        '📸 Progreso nuotraukos (kas 2 savaites)',
        '📊 Treniruočių log (Excel, aplikacija)',
        '✅ Kalendorius su X (kiekvieną dieną X = treniruotė atlikta)',
  '📝 Savijautos dienoraštis',
        '',
        '**Kodėl veikia:** Vizualinis progresas kuria "winning streak" efektą. Kai matai 10 X eilėje - nenori jo sulaužyti.',
        '',
        '**7. ACCOUNTABILITY (Atskaitomybė)**',
        'Žmonės, turintys accountability partner, 65% labiau pasiekia tikslus.',
        '',
        'Variantai:',
        '• Treniruočių partnerė (susitariate ir nenorit viena kitos apvilti)',
        '• Online bendruomenė (pvz., Renata Ladies grupė)',
        '• Treneris/coach',
        '• Viešas įsipareigojimas (Instagram, draugams)'
      ],
      desire: [
        '**Tikros Istorijos:**',
        '',
        '**Laura, 34m:** "Metai bandžiau \'motyvuotai\' sportuoti. Pradėdavau su entuziazmu, po 3 savaičių - žlugimas. Kai perėjau prie sistemos (treniruotės kalendorius + meal prep + accountability grupė), viskas pasikeitė. Jau 8 mėnesius nepraleidu nei vienos savaitės be 3 treniruočių."',
        '',
        '**Ieva, 28m:** "5 minučių taisyklė - mano gelbėjimas. Dauguma dienų galvoju \'nenoriu\'. Bet sakau sau \'tik apsirensk\'. Paskui \'tik 5 min\'. Ir beveik visada pasidaro pilna treniruotė. Jau 6 mėnesiai taip!"',
        '',
        '**Kas Daryti Kai Tikrai Išdegi:**',
        '**1. Deload savaitė:** Sumažink intensyvumą 50%. 3 treniruotės → 2. 60 min → 30 min.',
  '**2. Pakeisk rutiną:** Nuobodus bėgiojimas? Pamėgink šokius, plaukimą, krepšinį.',
  '**3. Grįžk į "KODĖL":** Kodėl pradėjai? Sveikata? Vaikai? Pasitikėjimas savimi? Užsirašyk ir perskaityk.',
  '**4. Prašyk pagalbos:** Kalbėk su treneriu, terapeutu ar drauge. Nebūk viena.',
        '',
        '**Disciplina ≠ Griežtumas**',
        'Disciplina nereiškia savęs kankinimo. Tai reiškia:',
        '• Nustatyti aiškius prioritetus',
        '• Sukurti sistemas',
  '• Būk lanksti (gyvenimas nutinka!)',
        '• Savęs pagarbą',
        '',
        '**80/20 Taisyklė:**',
        '80% laiko laikykis plano. 20% - būk lanksti. Jei maitiniesi sveikai 80% laiko, vienas pizza vakaras NESUGRIAUNS progreso.'
      ],
      action: [
        '**Tavo "Anti-Motyvacijos" Sistema - Įgyvendinti Per 7 Dienas:**',
        '',
        '**Diena 1: Apibrėžk Identity**',
        'Užpildyk: "Aš esu žmogus, kuris __________"',
        'Pavyzdys: "...rūpinasi savo kūnu", "...yra stipri", "...renkasi sveikatą"',
        '',
        '**Diena 2: Sukurk Treniruočių Kalendorių**',
        'Įtraukti į Google Calendar/telefono kalendorių KONKREČIAS treniruotes. Su laiku ir vieta.',
        '',
        '**Diena 3: Meal Prep**',
        'Paruošk bent 3 sveikus valgius savaitei. Dėk į konteinerius.',
        '',
        '**Diena 4: Aplinkos Optimizacija**',
  'Paruošk sportinius drabužius vakare. Pašalink saldumynus iš virtuvės.',
        '',
        '**Diena 5: If-Then Plans**',
        'Užsirašyk 3 "Jei-Tada" planus galimoms kliūtims.',
        '',
        '**Diena 6: Rask Accountability**',
        'Paprašyk draugės būti partnere ARBA prisijunk prie Renata Ladies bendruomenės.',
        '',
        '**Diena 7: Pirma Progress Nuotrauka**',
        'Nusifotografuok. Užsirašyk savijautę. Tai tavasis "Day 1".',
        '',
        '**Nori Pagalbos Sukurti Savo Sistemą?**',
        '',
        'Mūsų "Mindset & Habit Building" programoje gausi:',
        '• 8 savaičių habit building framework',
        '• Savaitiniai check-ins su manimi',
        '• Prieigą prie privačios Facebook grupės (accountability!)',
        '• Workbook su visomis užduotimis ir trackeriais',
        '• Monthly group coaching calls',
  '**[Sužinok apie programą →](/programos/mindset-habits)**',
        '',
        'Ar nori 1-on-1 coaching su manimi?',
  '**[Rezervuoti konsultaciją →](/konsultacijos)**',
        '',
  '**P.S.** Motyvacija yra kaip dušas – jos reikia kasdien. Bet disciplina? Tai pastatas. Nepajudinamas. Pradėk statyti šiandien. 🏗️💪'
      ]
    },
    seo: {
      metaTitle: 'Kaip Išlaikyti Motyvaciją Treniruotėms (2025) | Renata Ladies',
      metaDescription: 'Patvirtinti psichologijos būdai kaip išlikti motyvuotai ilgai. Disciplina, sistemos ir įpročiai kas tikrai veikia.',
      keywords: ['motyvacija treniruotėms', 'kaip nepasiduoti', 'disciplina', 'įpročių kūrimas', 'fitness motyvacija', 'habit building']
    }
  },
  {
    id: '6',
    slug: 'papildai-moterims-ko-tikrai-reikia',
    title: 'Papildai Moterims: Kas Tikrai Veikia ir Ko Nereikia (Ekspertės Gidas)',
    excerpt: 'Kurių papildų tikrai reikia moterims, treniruojančioms ir sveikai gyvenančioms? Apžvalga su moksliniais tyrimais.',
    category: 'Mityba',
    author: 'Renata Marcinkutė',
    publishedAt: '2025-09-15',
    readTime: '12 min',
    thumbnail: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&h=600&fit=crop&q=80',
    content: {
      attention: [
        'Įeik į bet kurią maisto papildų parduotuvę ir matysi šimtus produktų, žadančių stebuklus: "sudegink riebalus per 2 savaites", "pastatyk raumenis greitai", "detox organismą".',
        'Tiesa? 90% papildų yra arba visiškai nenaudingi, arba brangi šlapimo gamyba (jei viršytas poreikis, organizmas tiesiog išmeta).',
        'Šis straipsnis - tavo vadovas kaip nesuklysti ir išleisti pinigus tik tam, kas TIKRAI veikia ir paremta mokslu.'
      ],
      interest: [
        '**SVARBU: Aš nesu gydytoja. Prieš pradedant vartoti bet kokius papildus - pasikonsultuok su gydytoju, ypač jei turi sveikatos problemų arba vartoji vaistus.**',
        '',
        '**TOP 5 Papildai Kuriuos REKOMENDUOJU Moterims:**',
        '',
        '**1. VITAMINAS D3 (2000-4000 IU per dieną)**',
        '**Kodėl reikia:** Lietuvoje 80-90% gyventojų turi vitamino D deficitą (ypač žiemą). D vitaminas:',
        '• Palaiko imunitetą',
        '• Būtinas kaulų sveikatai',
        '• Gerina nuotaiką (padeda kovoti su depresija)',
        '• Svarbus hormonų gamybai',
        '• Padeda absorbuoti kalcį',
        '',
        '**Kas turėtų vartoti:** VISOS moterys, ypač rudenį/žiemą/pavasarį.',
        '**Dozė:** 2000 IU kasdien (žiemą gali didinti iki 4000 IU). Geriau vartoti su riebalais (pvz., su pusryčiais).',
        '**Kaina:** ~€5-10 už 3 mėnesių kursą.',
        '**Kas pasirinkti:** Ieškokite D3 (cholecalciferol), ne D2. Geros prekės ženklai: Swanson, Now Foods, Solgar.',
        '',
        '**2. OMEGA-3 (EPA/DHA) (1000-2000mg per dieną)**',
        '**Kodėl reikia:** Omega-3 riebalų rūgštys:',
        '• Mažina uždegimą organizme',
        '• Gerina širdies sveikatą',
        '• Palaiko smegenų funkciją',
        '• Gerina odos būklę',
        '• Padeda reguliuoti hormonus',
        '',
        '**Kas turėtų vartoti:** Moterys, kurios nevalgo žuvies 3+ kartus per savaitę.',
        '**Dozė:** 1000-2000mg EPA+DHA kartu (ne tik omega-3!). Žiūrėk etiketes - svarbu EPA ir DHA kiekis, ne bendras omega-3.',
        '**Kaina:** ~€15-25 už mėnesį (kokybiškas).',
        '**Patarimas:** Pirkite iš patikimų gamintojų (testuoti dėl sunkiųjų metalų). Vartokite su maistu.',
        '',
  '**3. MAGNIS (300-400 mg per dieną)**',
        '**Kodėl reikia:** Magnis dalyvauja 300+ biocheminėse reakcijose:',
        '• Gerina miego kokybę',
        '• Mažina stresą ir nerimą',
        '• Padeda raumenų atsigavimui',
        '• Svarbus energijos gamybai',
        '• Mažina PMS simptomus',
        '',
        '**Kas turėtų vartoti:** Moterys, kurios treniruojasi (prarandame magnį su prakaitu), patiria stresą, blogai miega.',
  '**Dozė:** 300-400 mg prieš miegą (padeda užmigti).',
  '**Forma:** Magnesium glycinate arba citrate (geriau absorbuojasi). Nevartokite magnio oksido – prastas įsisavinimas.',
        '**Kaina:** ~€10-15 už mėnesį.',
        '',
        '**4. BALTYMŲ MILTELIAI (Whey/Vegan) (20-30g per porciją)**',
        '**Kodėl reikia:** Ne papildas, bet maisto produktas. Padeda pasiekti dieninį baltymų poreikį (1.6-2g/kg).',
        '**Kas turėtų vartoti:** Moterys, kurios sunkiai suvalgo pakankamai baltymų iš normalaus maisto.',
        '**Kada vartoti:**',
        '• Po treniruotės (30 min lange)',
        '• Kaip užkandis',
        '• Pusryčiuose (smoothie)',
        '',
        '**Tipai:**',
        '• **Whey Isolate:** greičiausias įsisavinimas, mažai laktozės, idealus po treniruotės',
        '• **Whey Concentrate:** pigesnė, šiek tiek daugiau laktozės',
        '• **Vegan (žirnių/ryžių):** veganėms, laktozės netolerancijai',
        '',
        '**Dozė:** 1-2 porcijos per dieną (20-30g baltymų per porciją).',
        '**Kaina:** ~€20-40 už mėnesį.',
        '**Prekės ženklai:** Optimum Nutrition, MyProtein, Foodspring.',
        '',
        '**5. GELEŽIS (jei yra deficitas!) (14-18mg per dieną)**',
        '**Kodėl reikia:** Moterys praranda geležį per mėnesines. Geležies deficitas sukelia:',
  '• Nuovargį',
        '• Silpnumą',
        '• Plaukų slinkimą',
        '• Blankią odą',
        '• Sunkumus koncentruotis',
        '',
        '**Kas turėtų vartoti:** Moterys su sunkiomis mėnesinėmis, po gimdymo, vegetarės/veganės.',
  '**SVARBU:** Vartok tik jei PATIKRINAI kraujo tyrimais (feritinas, hemoglobinas). Per daug geležies – pavojinga!',
        '**Forma:** Geležies bisglicinatas (švelniausia skrandžiui).',
        '**Vartoti su:** Vitaminu C (gerina įsisavinimą). NEvartoti su kava/arbata (trukdo įsisavinimui).',
        '**Kaina:** ~€8-15 už mėnesį.'
      ],
      desire: [
        '**Papildai, Kurie GALBŪT Naudingi (Priklausomai Nuo Situacijos):**',
        '',
        '**• KREATIN MONOHIDRATAS (3-5g/dieną)**',
        'Jei keli sunkumus, nori didinti jėgą. Saugus moterims, padeda raumenų augimui.',
        '',
        '**• B GRUPĖS VITAMINAI**',
        'Jei esi veganė, turi energijos trūkumą. Ypač B12 (veganėms būtina!).',
        '',
        '**• PROBIOTIKAI**',
        'Jei turi virškinimo problemų, vartoji antibiotikų. Padeda žarnyno mikroflorai.',
        '',
        '**• KOLAGENAS (10g/dieną)**',
        'Jei turi sąnarių problemų, nori gerinti odos. Tyrimai rodo geresnę odos elastingumą.',
        '',
        '**Papildai, Kuriuos NEVARTOK (Pinigų švaistymas):**',
        '',
        '❌ **"FAT BURNERS" (Riebalų degintojai):** Dauguma neveikia. Kai kurie pavojingi (aukštas kofeinas, neištirti komponentai).',
  '❌ **DETOX ARBATOS:** Kūnas pats detoksikuoja per kepenis ir inkstus. Nereikia "detox".',
  '❌ **WAIST TRAINERS/KORSETO DIRŽAI:** Nesudegins riebalų. Tik sudeformuos organus.',
        '❌ **APPLE CIDER VINEGAR PILLS:** Nėra įrodymų, kad padeda mesti svorį.',
        '❌ **BCAA (jei jau vartoji pakankamai baltymų):** Whey proteinas jau turi BCAA.',
        '',
        '**Kaip Suprasti Ar Tau Reikia Papildų?**',
        '',
        '**Žingsnis 1: Kraujo Tyrimai**',
        'Pasitikrink bent kartą per metus:',
        '• Vitaminas D (25-OH)',
  '• Geležis (feritinas, hemoglobinas)',
        '• B12 (ypač jei veganė)',
        '• Magnis',
        '• Skydliaukės hormonai (TSH, T3, T4)',
        '',
        '**Žingsnis 2: Analizuok Mitybą**',
        'Ar gauni pakankamai iš maisto?',
        '• Omega-3: Valgai žuvį 3x/sav? → Jei ne, reikia papildų',
  '• Baltymai: Ar suvalgai 1,6 g/kg? → Jei ne, svarstyk proteino miltelius',
        '• D vitaminas: Ar kasdien esi 30+ min saulėje? → Jei ne (Lietuvoje - ne), reikia papildų',
        '',
        '**Kaip Teisingai Vartoti:**',
  '• **Su maistu:** D3, omega-3, geležis (mažesnis dirginimas skrandžiui)',
        '• **Prieš miegą:** Magnis',
        '• **Po treniruotės:** Baltymų milteliai',
        '• **Ryte:** B vitaminai',
        '',
        '**Budžeto Prioritetai:**',
        'Jei turi ribotą biudžetą, pirmiausia:',
        '1. D3 vitaminas (~€5/mėn) - BŪTINA',
        '2. Omega-3 (~€15/mėn) - labai svarbu',
  '3. Magnis (~€10/mėn) – jei blogam miegui/stresui',
        '4. Baltymų milteliai (~€30/mėn) - jei nesuvalgai pakankamai',
        '',
        'Suma: ~€30-60/mėn baziniams papildams.'
      ],
      action: [
        '**Tavo Action Plan - Pradėk Per 7 Dienas:**',
        '',
        '**☑ Diena 1: Užsiregistruok Kraujo Tyrimams**',
  'Skambink šeimos gydytojui arba privačioje laboratorijoje. Paprašyk: D vitaminas, geležis, B12, magnis.',
        '',
        '**☑ Diena 2-7: Laukiant Rezultatų**',
        'Gali jau pradėti vartoti D3 ir Omega-3 (praktiškai visiems reikia).',
        '',
        '**☑ Gavus Rezultatus:**',
        'Pasikonsultuok su gydytoju. Jei yra deficitų - papildai pagal rekomendacijas.',
        '',
        '**Kur Pirkti Kokybiškus Papildus Lietuvoje:**',
        '• **iHerb.com** (tarptautinė, platus pasirinkimas, dažnai akcijos)',
        '• **Myprotein.lt** (baltymams, sporto papildams)',
        '• **Bioderma.lt** (vitaminams, omega-3)',
        '• Vaistinės (Camelia, Eurovaistinė) - patikimi, bet brangesni',
        '',
        '**Ar Nori Personalizuoto Papildų Plano?**',
        '',
        'Mūsų "Sveikatos Optimizacija" programoje:',
        '• Analizuojame tavo kraujo tyrimus',
        '• Sudarome individualizuotą papildų planą',
        '• Rekomenduojame konkrečius produktus ir dozuotes',
        '• Stebime progresą ir koreguojame planą',
        '**[Sužinok apie programą →](/konsultacijos)**',
        '',
        'Turime ir RENATA LADIES parduotuvę su patikrintais papildais:',
        '**[Peržiūrėk papildus →](/papildai)**',
        '',
        '**P.S.** Papildai - tai PAPILDYMAS, ne pagrindas. Pirmiausia fokusas į tikrą maistą: daržoves, vaisius, baltymus, sveiką riebalus. Papildai tik užpildo spragas. Bet kai naudojami teisingai - gali būti game changer! 💊✨'
      ]
    },
    seo: {
      metaTitle: 'Papildai Moterims: Kas Veikia 2025 (Ekspertės Gidas)',
      metaDescription: 'Kurių papildų tikrai reikia moterims? D3, Omega-3, magnis, baltymai, geležis - moksliškai pagrįsta apžvalga ir dozuotės.',
      keywords: ['papildai moterims', 'vitaminai moterims', 'omega 3', 'd vitaminas', 'baltymų milteliai', 'maisto papildai']
    }
  },
  {
    id: '7',
    slug: 'meal-prep-pradedantiesiems',
    title: 'Meal Prep Pradedantiesiems: Kaip Paruošti Savaitės Valgį Per 2 Valandas',
    excerpt: 'Žingsnis po žingsnio vadovas kaip meal prep gali sutaupyti laiką, pinigus ir padėti valgyti sveikiau. Su pavyzdžiu ir shopping list.',
    category: 'Receptai',
    author: 'Renata Marcinkutė',
    publishedAt: '2025-09-10',
    readTime: '14 min',
    thumbnail: 'https://images.unsplash.com/photo-1610415946035-bad6fc9f5b8e?w=800&h=600&fit=crop&q=80',
    content: {
      attention: [
  'Pirmadienis 19:00. Grįžti iš darbo alkana ir išvargusi. Atidarai šaldytuvą... tuščia (beveik). Ką darai? Užsisakai Wolt. Trečią kartą šią savaitę.',
        'Jei tai skamba pažįstama, tu ne viena. Vidutinė Lietuvos šeima išleidžia €200-300/mėn maisto pristatymui. Per metus - €2,400-3,600! 😱',
        'Meal prep - tai ne "bodybuilderių dalykas". Tai būdas kaip sutaupyti laiką, pinigus ir valgyti sveikiau be streso. Ir yra DAUG lengviau nei manai!'
      ],
      interest: [
        '**Kas Yra Meal Prep?**',
        'Meal Preparation = maisto paruošimas iš anksto. Paprastai sekmadienį paruoši 5-7 dienų valgius, sudėti į konteinerius, šaldytuvą/šaldiklį.',
        '',
        '**Privalumai:**',
        '✅ Sutaupo LAIKO: 2h sekmadienį vs 1h+ kasdien virtuvėje',
        '✅ Sutaupo PINIGŲ: ~€50-100/mėn (vs maisto pristatymas)',
        '✅ SVEIKESNIS: kontroliuoji ingredientus, porcijas, kalorijas',
        '✅ Mažiau STRESO: nereikia kasdien galvoti "ką valgysiu?"',
        '✅ Mažiau ŠVAISTOMO maisto: naudoji viską, ką perki',
        '',
        '**3 Meal Prep Stiliai:**',
        '',
        '**1. Visas Valgis Prep (Beginner-Friendly)**',
        'Paruoši pilnus valgius, sudėti į konteinerius. Tiesiog pašildai ir valgai.',
        '*Idealus:* labai užsiėmusiems žmonėms',
        '',
        '**2. Komponentų Prep (Mano Favorittas)**',
        'Paruoši atskirus komponentus (baltymus, angliavandenius, daržoves). Derinį kasdien pagal nuotaiką.',
        '*Idealus:* tiems, kas nori įvairovės',
        '',
        '**3. Mix Prep**',
        'Kai kurie valgiai pilnai paruošti (pietūs), kiti - tik komponentai (vakarienė).',
        '*Idealus:* balansas tarp patogumo ir įvairovės',
        '',
        '**Ko Tau Reikia Pradėti:**',
        '',
        '**Įranga (~€30-50 investicija):**',
        '• 10-15 stiklinių/plastiko konteinerių (mikrobangu saugūs)',
        '• 2-3 dideli kepimo skardai',
        '• Geri peiliai',
        '• Didelė keptuvė/puodas',
        '',
        '**Nereikia:** Brangios įrangos, 10 skirtingų prieskonių, kulinarinių įgūdžių!',
        '',
        '**ŽINGSNIS PO ŽINGSNIO: Tavoji Pirma Meal Prep Sekmadienis**',
        '',
        '**ŽINGSNIS 1: PLANUOK (Penktadienį, 15 min)**',
        '',
        'Nuspręsk:',
        '• Kiek dienų ruoši? (Pradėk nuo 4-5 dienų)',
        '• Kiek valgių per dieną? (Pietūs + vakarienė = lengviausia)',
        '• Kokius makroelementus tikslas? (Baltymai, angliavandeniai, riebalai)',
        '',
        '**Paprasta Formulė Kiekvienam Valgiui:**',
        '🥩 Baltymų šaltinis (150-200g): vištiena, žuvis, jautiena, tofu',
        '🍚 Angliavandenių šaltinis (100-150g): ryžiai, kvinoja, saldžiosios bulvės, pasta',
        '🥦 Daržovės (150-200g): brokoliai, špinatas, morkos, cukinija',
        '🥑 Sveiki riebalai (15-20g): alyvuogių aliejus, avokadas, riešutai',
        '',
        '**ŽINGSNIS 2: SHOPPING LIST (Šeštadienį)**',
        '',
        '**Pavyzdys 5 dienų pietums ir vakarienėms:**',
        '',
        '**Baltymai:**',
        '• 1kg vištienos krūtinėlių',
        '• 800g lašišų filė',
        '• 500g kalakutienos maltų',
        '',
        '**Angliavandeniai:**',
        '• 1kg rudųjų ryžių',
        '• 1kg saldžiųjų bulvių',
        '• 500g kvinojos',
        '',
        '**Daržovės:**',
        '• 1kg brokolių',
        '• 1kg pomidorų',
        '• 500g špinato',
        '• 500g morkų',
        '• 3 paprikos',
        '• 1 cukinija',
        '',
        '**Riebalai & Prieskoniai:**',
        '• Alyvuogių aliejus',
        '• Druska, pipirai, česnakų milteliai, citrinos',
        '',
        '**Kaina:** ~€35-45 už 10 valgių = €3.50-4.50/valgis (vs €8-12 Wolt)',
        '',
        '**ŽINGSNIS 3: PREP DAY (Sekmadienis, 2-2.5h)**',
        '',
        '**9:00-9:15: Paruošimas**',
        '• Išsiimt visus produktus',
        '• Išplauti daržoves',
        '• Įkaitinti orkaitę 200°C',
        '• Paruošti konteinerius',
        '',
        '**9:15-9:45: Pjaustyk Daržoves**',
        '• Saldžiąsias bulves į kubelius',
        '• Brokolius į žiedus',
        '• Paprikas į juosteles',
        '• Cukinija į griežinelius',
        '',
        '**9:45-10:15: Orkaitėje (Batch #1)**',
        '• Skardon: saldžiosios bulvės + alyvuogių aliejus + druska → 25-30 min',
        '• Skardon: vištienos krūtinėlės + prieskoniai → 25-30 min',
        '',
        '**10:15-10:45: Virimas**',
        '• Puode: išvirk 500g ryžių (seks 15 min)',
        '• Puode: išvirk 250g kvinojos',
        '',
        '**10:45-11:15: Orkaitėje (Batch #2)**',
        '• Skardon: lašiša + citrinos + žolelės → 15-18 min',
        '• Skardon: brokoliai + aliejus → 20 min',
        '',
        '**11:15-11:30: Keptuvė**',
        '• Apkepk kalakutienos maltes su pomidorais, česnaku, prieskoniais (pasta/ryžių padažas)',
        '',
        '**11:30-11:45: DĖLIOK Į KONTEINERIUS**',
        '',
        '**Pietūs (5 konteineriai):**',
        '• 150g vištienos',
        '• 120g rudųjų ryžių',
        '• 150g brokolių',
        '',
        '**Vakarienė (5 konteineriai):**',
        '• 150g lašišos',
        '• 150g saldžiųjų bulvių',
        '• Daržovių mišinys',
        '',
        '**11:45-12:00: VALYMAS & LAIKYMAS**',
        '• Sudėk į šaldytuvą (2-3 dienos)',
        '• Sudėk į šaldiklį (4-5 diena)',
        '• Išplaukite indus',
        '',
        '**DONE! 🎉**'
      ],
      desire: [
        '**Meal Prep Pro Patarimai:**',
        '',
        '**1. ĮVAIRINK PRIESKONIUS**',
        'Tas pats vištiena + ryžiai + brokoliai gali būti:',
        '• Pirmadienis: Azijietiški (sojų padažas, imbierais)',
        '• Trečiadienis: Itališki (bazilikas, oregano, pomidorai)',
        '• Penktadienis: Meksikietiški (kuminas, čili, koriandras)',
        '',
        '**2. LAIKYK TEISINGAI**',
        '• Šaldytuve: 3-4 dienos (po to kokybė blogėja)',
        '• Šaldiklyje: iki 3 mėnesių',
        '• Atšildyk šaldytuve per naktį arba mikrobangų krosnelėje',
        '',
        '**3. NUSIBOS? ŠALDYK**',
        'Jei paruoši per daug arba tiesiog nusibodo - šaldyk. Turėsi "emergency meal" blogai dienai.',
        '',
        '**4. BALANSAS**',
        'Ne viskas turi būti meal prep. Gali būti:',
        '• Pietūs = meal prep',
        '• Pusryčiai = greitas (jogurtas, kiaušiniai)',
        '• Vakarienė = šviežiai virti (šeštadienį/sekmadienį)',
        '',
        '**Dažniausios Klaidos (IR Kaip Jų Vengti):**',
        '',
        '❌ **Klaida #1: Per daug ambicinga**',
        '✅ Sprendimas: Pradėk nuo 4-5 dienų, 1-2 valgių. Palaipsniui didink.',
        '',
        '❌ **Klaida #2: Per sudėtingi receptai**',
        '✅ Sprendimas: Paprasti = gerai. Kepti/virti = geriausi metodai meal prep.',
        '',
        '❌ **Klaida #3: Visko ta pati**',
        '✅ Sprendimas: Paruošk 2-3 skirtingus baltymus, 2 angliavandenių variantus. Derinį kasdien.',
        '',
        '❌ **Klaida #4: Blogos konteineriai**',
        '✅ Sprendimas: Investuok į kokybišką stiklinius/plastikus (BPA-free). Mikrobangų saugūs.',
        '',
        '**Meal Prep su Biudžetu:**',
        '',
        '**Budget-Friendly Ingredientai:**',
        '• Baltymai: kiaušiniai, vištiena (ne filė, bet šlaunelės), tuna konservuota, pupelės',
        '• Angliavandeniai: avižos, ryžiai, makaronai, duona',
        '• Daržovės: šaldytos daržovės (pigesnės, ilgai laikosi!), sezoninės daržovės',
        '',
        '**Savaitės Meal Prep už €25:**',
        '• 2kg vištienos šlaunelių (€8)',
        '• 1kg ryžių (€2)',
        '• 2kg šaldytų daržovių mišinio (€6)',
        '• 12 kiaušinių (€3)',
        '• Avižos 1kg (€2)',
        '• Prieskoniai/aliejus (€4)',
        '',
        '= 10-12 valgių = ~€2-2.50/valgis!'
      ],
      action: [
        '**Tavo Pirmo Meal Prep Planas - START Šį Savaitgalį:**',
        '',
        '**☑ PENKTADIENIS (Vakaras):**',
        '• Nuspręsk: 4 dienos, pietūs + vakarienė = 8 valgiai',
        '• Pasirink: 2 baltymų šaltinius, 2 angliavandenių, 3-4 daržovės',
        '• Užsirašyk shopping list',
        '',
        '**☑ ŠEŠTADIENIS:**',
        '• Nusipirk produktus (NESIRINK alkanas!)',
        '• Pasitikrink ar turi pakankamai konteinerių',
        '',
  '**☑ SEKMADIENIS (9:00-11:30):**',
  '• Atlik aukščiau aprašytus žingsnius',
        '• Užrašyk kiek laiko užtruko (kitą kartą bus greičiau!)',
        '',
        '**☑ PIRMADIENIS-KETVIRTADIENIS:**',
        '• Mėgaukis patogumo! Tiesiog pašildyk ir valgai',
        '• Stebėk kaip jaučiesi (energija, laikas sutaupytas)',
        '',
        '**Nori Pagalbos Pradėti?**',
        '',
        'Mūsų "Meal Prep Masterclass" programoje gausi:',
        '• 4 savaičių meal prep planus (su shopping lists)',
        '• 50+ meal prep receptų',
        '• Video tutorial kaip efektyviai ruošti',
        '• Porcijų skaičiuoklę pagal tavo tikslus',
        '• Prieigą prie privačios FB grupės (klausimai/atsakymai)',
        '**[Sužinok apie programą →](/mitybos-planai)**',
        '',
        'Ar nori individualizuoto mitybos ir meal prep plano?',
        '**[Rezervuoti konsultaciją →](/konsultacijos)**',
        '',
        '**P.S.** Pirmasis meal prep gali atrodyti bauginantis. Bet po 2-3 kartų - taps rutina. O laikas ir pinigai, kuriuos sutaupysi? Priceless! Pradėk mažai, tobulėk laipsniškai. Tu gali! 🍱💪'
      ]
    },
    seo: {
      metaTitle: 'Meal Prep Pradedantiesiems 2025 (Žingsnis Po Žingsnio)',
      metaDescription: 'Kaip paruošti savaitės valgį per 2 valandas? Pilnas meal prep gidas su shopping list, laiko grafiku ir biudžeto patarimais.',
      keywords: ['meal prep', 'maisto ruošimas', 'meal prep pradedantiesiems', 'kaip meal prep', 'sveika mityba', 'meal prep receptai']
    }
  },
  {
    id: '8',
    slug: 'kardio-vs-jegos-treniruotes',
    title: 'Kardio vs Jėgos Treniruotės: Kas Geriau Svorio Metimui?',
    excerpt: 'Amžinas ginčas: bėgimas ar sunkumai? Sužinok ką sako mokslas ir kaip kombinuoti abu optimaliam rezultatui.',
    category: 'Treniruotės',
    author: 'Renata Marcinkutė',
    publishedAt: '2025-08-25',
    readTime: '11 min',
    thumbnail: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&h=600&fit=crop&q=80',
    content: {
      attention: [
        'Scenarijus A: Laura bėgioja 5 kartus per savaitę po 45 min. Po 3 mėnesių numeta 4 kg, bet vis dar "liekna-storulė" forma.',
  'Scenarijus B: Ieva kelia sunkumus 4 kartus per savaitę. Po 3 mėnesių sveria tą patį, bet atrodo 5 kg lengvesnė – suformavusi, visiškai kita.',
  'Tai kuri teisi? Atsakymas: ABI. Bet priklausomai nuo tavo tikslo, viena gali būti geresnė. Paaiškinsiu.'
      ],
      interest: [
        '**Kas Yra Kardio?**',
        'Cardiovascular training = pratimas širdžiai ir plaučiams. Pakelia širdies ritmą ilgesniam laikui.',
        '',
        '**Tipai:**',
        '• **LISS (Low-Intensity Steady State):** Ilgas, lėtas kardio (pvz., 45 min greitas ėjimas)',
        '• **MISS (Moderate):** Vidutinis intensyvumas (pvz., lengvas bėgimas)',
        '• **HIIT (High-Intensity Interval Training):** Trumpi, intensyvūs intervalai + poilsis',
        '',
        '**Kardio Privalumai:**',
        '✅ Sudegina daug kalorijų PER treniruotę (300-600 kcal/h)',
        '✅ Gerina širdies ir kraujagyslių sveikatą',
        '✅ Padidina ištvermę',
        '✅ Mažina streso lygį (endorfinai!)',
        '✅ Lengva pradėti (nereikia inventoriaus)',
        '',
        '**Kardio Trūkumai:**',
        '❌ NEDIDELĖ "afterburn" (mažai kalorijų po treniruotės)',
        '❌ Gali deginti raumenis (ilgas, dažnas kardio)',
        '❌ Adaptacija (kūnas pripranta, reikia didinti intensyvumą)',
        '❌ Neformuoja raumenų',
        '',
        '**Kas Yra Jėgos Treniruotės?**',
        'Resistance training = raumenų treniravimas su pasipriešinimu (svoriai, guma, kūno svoris).',
        '',
        '**Tipai:**',
        '• **Bodybuilding:** Didelis tūris, raumenų hipertrofijai',
        '• **Powerlifting:** Mažas kartojimų, maksimali jėga',
        '• **Functional:** Funkciniai judėjimai (squats, deadlifts)',
        '',
        '**Jėgos Treniruočių Privalumai:**',
        '✅ Stato/saugo raumenis (net kalorijų deficite!)',
        '✅ Padidina bazinį metabolizmą (raumenys = kalorijų degimas 24/7)',
        '✅ "Afterburn" efektas (EPOC - dega kalorijas iki 48h po treniruotės)',
        '✅ Formuoja kūną ("toned" išvaizdą)',
        '✅ Stiprina kaulus (svarbu moterims!)',
        '✅ Gerina laikyseną ir funkcinį judėjimą',
        '',
        '**Jėgos Treniruočių Trūkumai:**',
        '❌ Mažiau kalorijų sudeginama PER treniruotę (200-400 kcal/h)',
        '❌ Reikia inventoriaus/sporto klubo',
        '❌ Mokymosi kreivė (technika svarbi)',
  '❌ Gali jaustis bauginantis pradžioje (ypač moterims salėje)',
        '',
        '**KAS GERIAU SVORIO METIMUI?**',
        '',
  '**Trumpas atsakymas: JĖGOS TRENIRUOTĖS + šiek tiek kardio**',
        '',
        '**Ilgas atsakymas (su mokslu):**',
        '',
        '**Tyrimas #1 (Duke University, 2012):**',
        '• Grupė A: Tik kardio → numeta 1.8 kg',
        '• Grupė B: Tik jėgos → numeta 0.9 kg (bet -2% kūno riebalų)',
        '• Grupė C: Kardio + jėgos → numeta 2.5 kg + -3% riebalų',
        '',
        '**Išvada:** Kombinacija geriausia.',
        '',
        '**Tyrimas #2 (Journal of Applied Physiology):**',
        'Moterys kalorijų deficite (12 savaičių):',
        '• Tik dieta: -5 kg (3 kg riebalų + 2 kg raumenų) 😢',
        '• Dieta + kardio: -6 kg (4 kg riebalų + 2 kg raumenų)',
        '• Dieta + jėgos: -5 kg (5 kg riebalų + 0 kg raumenų) 🎉',
        '',
        '**Išvada:** Jėgos treniruotės SAUGO raumenis kalorijų deficite!',
        '',
        '**METABOLIZMO MATEMATIKA:**',
        '',
        '1 kg raumenų sudegina ~13 kcal/dieną ramybėje',
        '1 kg riebalų sudegina ~4 kcal/dieną',
        '',
        'Jei turi 5 kg daugiau raumenų = +65 kcal/dieną = +24,000 kcal/metus = ~3 kg riebalų per metus BE NIEKO NEDARYTI! 🤯',
        '',
        '**IDEALI PROGRAMA SVORIO METIMUI:**',
        '',
        '**Prioritetas #1: JĖGOS TRENIRUOTĖS**',
        '• 3-4 kartus per savaitę',
        '• 45-60 min',
        '• Visa kūno programa arba upper/lower split',
        '• Progresyvi perkrova (didink svorius kas savaitę)',
        '',
        '**Prioritetas #2: KARDIO (Papildomas)**',
        '• 2-3 kartus per savaitę',
        '• 20-30 min HIIT ARBA 45-60 min LISS',
        '• Galima atskirą dieną arba PO jėgos treniruotės',
        '',
        '**Prioritetas #3: NEAT (Kasdienė veikla)**',
        '• 10,000 žingsnių per dieną',
        '• Laiptais, ne liftu',
        '• Parkuoti toliau',
        '• Stovėti, ne sėdėti',
        '',
        '**SAVAITĖS GRAFIKO PAVYZDYS:**',
        '',
        '**Pirmadienis:** Jėgos (apatinė dalis - squats, lunges, tiltas) + 15 min HIIT',
        '**Antradienis:** 30 min LISS (greitas ėjimas) + yoga',
        '**Trečiadienis:** Jėgos (viršutinė dalis - push-ups, rows, shoulder press)',
        '**Ketvirtadienis:** Poilsis/tempimas',
        '**Penktadienis:** Jėgos (visa kūno) + 20 min HIIT',
        '**Šeštadienis:** 45-60 min LISS (pvz., dviračio trasa)',
        '**Sekmadienis:** Aktyvus poilsis (pasivaikščiojimas, šokiai)',
        '',
        'Bendrai: 3 jėgos, 2-3 kardio, 1 aktyvus poilsis = Optimalu!'
      ],
      desire: [
        '**MITAI, KURIUOS REIKIA SUNAIKINTI:**',
        '',
        '**Mitas #1: "Jėgos treniruotės padarys mane didelę/masyvią"**',
        '❌ MELAS! Moterys turi 15-20x mažiau testosterono nei vyrai. Labai sunku "išaugti". Kas matosi Instagram - dažnai steroidai arba metų darbas + specifinis mityba.',
        '✅ TIESA: Jėgos treniruotės padarys tave "toned", suformuos, bet ne "masyvią".',
        '',
        '**Mitas #2: "Kardio geriau riebalams deginti"**',
        '❌ PUSĖ TIESOS: Kardio sudegina daugiau PER treniruotę, bet jėgos - daugiau ilgalaikėje perspektyvoje (afterburn + raumenų metabolizmas).',
        '',
        '**Mitas #3: "Galiu valgyti viską jei darysiu kardio"**',
        '❌ MELAS! Negali "outrun bad diet". 1 Big Mac = 550 kcal = 1 valanda bėgimo. Mityba = 70% rezultato.',
        '',
        '**Mitas #4: "Jėgos treniruotės ne man - per sena/silpna/neturiu patyrimo"**',
        '❌ MELAS! Jėgos treniruotės tinka VISIEMS amžiams. Pradėk su kūno svoriu, lengvais svoriais, progresija laipsniškai.',
        '',
        '**KAM KAS TINKA:**',
        '',
        '**Fokusas į KARDIO jei:**',
        '• Ruošies maratonui/triathlonui',
        '• Pradini treniruotis ir bauginiesi svorių',
        '• Turi daug svorio mesti ir sąnariai skauda (LISS geriau)',
        '• Tiesiog mėgsti bėgti/dviračiu važiuoti',
        '',
        '**Fokusas į JĖGOS jei:**',
        '• Nori "toned" kūno',
        '• Nori ilgalaikio metabolizmo padidinimo',
        '• Svarbu raumenų/kaulų sveikata',
        '• Turi ribotą laiką (jėgos efektyvesnės)',
        '',
        '**Kombinacija jei:**',
        '• Nori geriausio iš abiejų pasaulių (rekomenduoju!)',
        '• Nori maksimalaus riebalų deginimo',
        '• Mėgsti įvairovę',
        '',
        '**TIKROS MOTERŲ PATIRTYS:**',
        '',
        '**Laura, 32m:** "5 metus bėgiojau 5x/savaitę. Atrodžiau \'skinny fat\'. Kai pradėjau kelti svorius ir sumažinau kardio iki 2x/sav - per 6 mėn pasikeitė viskas. Turiu raumenis, sėdmenis, pečius. Svoris tas pats, bet atrodymas VISIŠKAI kitoks."',
        '',
  '**Ieva, 28m:** "Bijojau sporto klubo svorių zonos. Pradėjau su kūno svoriu namuose (squats, push-ups). Po 3 mėn jaučiausi pasiruošusi salei. Dabar keliu deadlift – 60 kg ir jaučiuosi kaip superherojė! 💪"'
      ],
      action: [
        '**Tavo 4 Savaičių "Kardio + Jėgos" Planas:**',
        '',
        '**1-2 Savaitės (Adaptacija):**',
        '• 3x jėgos (pilnas kūnas, lengvi svoriai, 12-15 kartojimų)',
        '• 2x LISS (30 min greitas ėjimas)',
        '• Tikslas: išmokti techniką, pripratinti kūną',
        '',
        '**3-4 Savaitės (Progresija):**',
        '• 4x jėgos (upper/lower split, didesni svoriai, 8-12 kartojimų)',
        '• 2x kardio (1x HIIT 20 min, 1x LISS 45 min)',
        '• Tikslas: didinti intensyvumą',
        '',
        '**Po 4 Savaičių:**',
        'Vertink rezultatus (svoris, nuotraukos, apimtys, jėga). Koreguok planą pagal tikslus.',
        '',
        '**Nereikia Sporto Klubo? Namų Versija:**',
        '',
        '**Jėgos (be inventoriaus):**',
        '• Squats, lunges (kojoms)',
        '• Push-ups, plank (viršutinė dalis)',
        '• Glute bridge (sėdmenys)',
        '• Dips nuo kėdės (tricepsai)',
        '',
        '**Kardio (be inventoriaus):**',
        '• Jumping jacks',
        '• Burpees',
        '• Mountain climbers',
        '• High knees',
        '',
        '**Nori Pilną Programą?**',
        '',
        'Mūsų "Hybrid Training" programoje gausi:',
        '• 12 savaičių jėgos + kardio planą',
        '• Video instrukcijos kiekvienam pratimui',
        '• Namų IR sporto klubo versijas',
        '• Progresijos sistemą',
        '• Mitybos gaires rezultatams maksimizuoti',
        '**[Peržiūrėk programas →](/programos)**',
        '',
        'Ar nori 1-on-1 treniruočių plano?',
        '**[Rezervuoti konsultaciją →](/konsultacijos)**',
        '',
        '**P.S.** Neturi būti "kardio mergina" arba "jėgos mergina". Gali būti ABIEJŲ! Geriausias kūnas kuriamas su balansu. Pradėk nuo to, kas tau patinka, ir laipsniškai pridėk kitą. Svarbu judėti - kaip judėsi, nuspręsi pati! 🏃‍♀️💪'
      ]
    },
    seo: {
      metaTitle: 'Kardio vs Jėgos Treniruotės 2025 (Kas Geriau Svoriui?)',
      metaDescription: 'Bėgimas ar sunkumai svorio metimui? Sužinok ką sako mokslas ir kaip kombinuoti kardio + jėgos treniruotes optimaliam rezultatui.',
      keywords: ['kardio vs jėgos', 'svorio metimas', 'kardio treniruotės', 'jėgos treniruotės moterims', 'kas geriau svoriui', 'hiit workout']
    }
  },
  {
    id: '9',
    slug: 'transformacija-istorija-10kg',
    title: 'Tikra Transformacijos Istorija: Kaip Numečiau 10 kg ir Atradau Savęs',
    excerpt: 'Mano asmeninė kelionė nuo nesveikų įpročių iki sveiko, stipraus kūno. Be filtrų, be melo - tik tiesa.',
    category: 'Motyvacija',
    author: 'Renata Marcinkutė',
    publishedAt: '2025-08-15',
    readTime: '13 min',
    thumbnail: 'https://images.unsplash.com/photo-1434682772747-f16d3ea162c3?w=800&h=600&fit=crop&q=80',
    content: {
      attention: [
        '*Straipsnis parašytas pirmuoju asmeniu - mano asmeninė istorija, kuria dalinuosi su jumis.*',
        '',
        '2018 metų gruodis. Stoviu prieš veidrodį ir neatpažįstu savęs. Ne vien dėl svorio (nors taip, +15 kg virš normalaus). Dėl to, kas matau akyse - tuštuma, nusivylimas, pasidavimas.',
        'Kaip čia atsidūriau? Dar prieš 3 metus buvau aktyvi, sportuojanti, laiminga. O dabar? Fast food 4x/savaitę, sporto klubo abonementas nenaudojamas 8 mėnesius, miegas 5h/naktį, streso lygis - kosmose.',
        'Tą dieną nusprendžiau: UŽTENKA. Bet ne kitą pirmadienį. Ne nuo Naujų Metų. DABAR.'
      ],
      interest: [
        '**PRADŽIA (2019 m. Sausio 2):**',
        '',
        '**Pradinės statistikos:**',
        '• Svoris: 78 kg (ūgis 168 cm)',
        '• Kūno riebalai: ~35%',
        '• Energijos lygis: 2/10',
        '• Pasitikėjimas savimi: 1/10',
  '• Mityba: chaotiška (nuo alkio iki persivalgymo)',
        '• Treniruotės: 0x/savaitę',
        '',
        '**Klaidų, Kurias Padariau (Kad Tu Jų Nedarytum):**',
        '',
        '**Klaida #1: Pradėjau per agresyviai**',
        'Ką dariau: Iškart 1200 kcal/dieną + treniruotės 6x/savaitę + visiškas cukraus atsisakymas.',
        'Kas nutiko: Po 2 savaičių - išdegimas. Binge eating. Žlugimas.',
        '**Pamoka:** Pokyčiai turi būti tvarūs, ne ekstremalūs.',
        '',
        '**Klaida #2: Lyginau save su Instagram**',
        'Sekiau fitness influencer su tobulais kūnais. Jaučiausi beviltiškai.',
        '**Pamoka:** Jų "transformacija 12 savaičių" dažnai yra metų darbas + photoshop. Tavo kelionė - unikali.',
        '',
        '**Klaida #3: Ignoravau psichologinę dalį**',
        'Fokusas tik į mitybą ir treniruotes. Ignoravau stresą, miego stoką, emocijas.',
        '**Pamoka:** Sveikata - holistinė. Kūnas + protas + dvasia.',
        '',
  '**KAS PASIKEITĖ (Antras bandymas – 2019 m. vasaris):**',
        '',
        'Šį kartą padariau kitaip:',
        '',
        '**MITYBA:**',
        '• Skaičiavau kalorijas, bet realistiškos (1600-1700 kcal)',
        '• 80/20 taisyklė (80% sveiko, 20% "malonumų")',
        '• Meal prep sekmadieniais',
        '• Daug baltymų (140-150g/dieną)',
        '• Leidau sau "cheat meal" (ne dieną!) kartą per savaitę',
        '',
        '**TRENIRUOTĖS:**',
        '• Pradėjau su 3x/sav (ne 6!)',
        '• 2x jėgos (visa kūno programa)',
        '• 1x kardio (LISS - greitas ėjimas)',
        '• Laipsniškai didinau intensyvumą',
        '',
        '**MIEGAS:**',
        '• Tikslas: 7-8h/naktį',
        '• Režimas: miegoti ~23:00, keltis ~7:00',
        '• Jokių ekranų 1h prieš miegą',
        '',
        '**MINDSET:**',
  '• Dėmesys į PROCESĄ, ne rezultatą',
        '• Šventimas mažų laimėjimų',
        '• Dienoraštis (jausmai, progresas)',
        '• Vizualizacija',
        '',
        '**REZULTATAI PO 3 MĖNESIŲ:**',
        '• Svoris: 72 kg (-6 kg)',
        '• Energijos lygis: 7/10',
        '• Jėga: +30% visuose pratimuose',
  '• Miegas: žymiai geresnis',
        '• Nuotaika: pastebiamai geriau',
        '',
  'Bet svarbiausia? **Jaučiausi tvari.** Tai nebuvo dieta – tai buvo gyvenimo būdas.',
        '',
        '**SUNKŪS MOMENTAI (Nes Ne Viskas Buvo Lengva):**',
        '',
        '**Mėnuo 4 - Plato (Plateau):**',
        'Svoris sustojo 71 kg ir nejudėjo 3 savaites. Frustracija!',
  '**Ką dariau:** Perskaičiavau kalorijas (metabolizmas sulėtėjo), pridėjau daugiau kardio, turėjau „refeed“ dieną (daugiau angliavandenių).',
        '**Rezultatas:** Po 2 savaičių svoris vėl pradėjo kristi.',
        '',
        '**Mėnuo 5 - Gimtadienis:**',
        'Draugės gimtadienis. Tortas, pica, vynas. Valgiau. DAUG.',
        '**Ką jaučiau:** Kaltę. Norėjau "bausti" save extra treniruote ir badauti kitą dieną.',
        '**Ką TIKRAI dariau:** Priėmiau. Viena diena nesugadins progreso. Kitą dieną - tiesiog grįžau į normalų režimą.',
        '**Pamoka:** 1 blogas valgis ≠ žlugimas. Tęsk toliau.',
        '',
        '**REZULTATAI PO 6 MĖNESIŲ:**',
        '• Svoris: 68 kg (-10 kg iš pradžios!)',
        '• Kūno riebalai: ~25% (buvo 35%)',
        '• Energijos lygis: 9/10',
        '• Pasitikėjimas savimi: 8/10',
        '• Treniruotės: 4x/savaitę (mėgaujuosi!)',
        '• Mityba: intuityvi, sveika, be obsesijos',
        '',
        '**Drabužiai:** Iš 42 dydžio → 38',
        '**Svarbiausia:** Atradau STIPRUMĄ. Ne tik fiziniu, bet psichologiniu.'
      ],
      desire: [
        '**KĄ IŠMOKAU PER ŠIĄ KELIONĘ:**',
        '',
        '**1. JŪSŲ KELIONĖ ≠ KITO KELIONĖ**',
        'Kažkas numeta 10 kg per 8 savaites. Man užtruko 6 mėnesius. Ir kas? Mano rezultatas tvarūs. Jų - galbūt grįš.',
        '',
        '**2. DISCIPLINA > MOTYVACIJA**',
        'Motyvacija ateina ir išeina. Disciplina - sistema, kuri veikia net kai nesinori.',
        '',
        '**3. MITYBA = 70%, TRENIRUOTĖS = 30%**',
        'Negali "outwork" blogos mitybos. Bet negali ir turėti gražaus kūno be treniruočių.',
        '',
        '**4. SKALĖ - NE VIENINTELIS RODIKLIS**',
        'Yra savaitės kai svoris kilo (+1kg vanduo), bet drabužiai sėdėjo laisviau. Stebėk: apimtys, nuotraukos, savijautą.',
        '',
        '**5. MIEGAS IR STRESAS - NEMATOMI FAKTORIAI**',
        'Blogai miegos savaitė = svoris nekrysta net su tobula mityba. Stresui = kortizolis = stuburas svoris.',
        '',
        '**6. BENDRUOMENĖ SVARBI**',
        'Draugės, kurios palaikė (ir su kuriomis galėjau meal prep kartu) - didžiulė pagalba.',
        '',
        '**7. PAMYLĖK PROCESĄ**',
        'Kai pradėjau džiaugtis treniruotėmis, meal prep, sveiku maistu - rezultatai atėjo savaime.',
        '',
  '**KAIP GYVENU ŠIANDIEN (2025):**',
        '',
        '**Statistika:**',
        '• Svoris: 66-68 kg (stabilus)',
        '• Kūno riebalai: ~22%',
        '• Treniruotės: 4-5x/savaitė (mėgaujuosi!)',
        '• Mityba: intuityvi, 80/20',
        '• Energija: 9/10',
        '• Pasitikėjimas: 10/10',
        '',
        '**Kas pasikeitė virš skaičių:**',
  '• Prabundu 6:00 BE žadintuvo, pilna energijos',
        '• Mėgaujuosi treniruotėmis (ne "turiu", o "noriu")',
        '• Laisva santykiu su maistu (galiu valgyti tortą be kaltės)',
  '• Jaučiuosi STIPRI (deadlift – 80 kg! 💪)',
        '• Įkvepiu kitas moteris',
        '',
        '**AR BUVO VERTA?**',
        '',
        'ABSOLIUČIAI TAIP. Bet ne dėl numerio ant skalės.',
        '',
        'Verta dėl:',
        '• Pasitikėjimo, kurį atradau',
        '• Draugių, kurias sutikau bendruomenėje',
        '• Disciplinos, kuri perkeliama į visas gyvenimo sritis',
        '• Žinojimo, kad AŠ GALIU',
        '',
        'Kūnas pasikeitė. Bet svarbiausia - pasikeitė mano MIND.'
      ],
      action: [
        '**JŪSŲ TRANSFORMACIJA PRASIDEDA DABAR:**',
        '',
        'Jei skaitai šį straipsnį, tikriausiai esi panašioje vietoje kaip aš buvau 2019-ųjų sausį.',
        '',
        'Noriu tau pasakyti:',
        '',
        '**TU GALI.**',
        '',
        'Gali atrodyti neįmanoma. Bet vienas žingsnis vienu metu - ir po 6 mėnesių atsigręši ir neatpažinsi savęs.',
        '',
        '**Tau Nereikia:**',
        '❌ Tobulos motyvacijos',
        '❌ Begalės laiko',
        '❌ Brangaus sporto klubo',
        '❌ Pažengusių įgūdžių',
        '',
        '**Tau Reikia:**',
        '✅ Sprendimo PRADĖTI',
        '✅ Nuoseklumo',
        '✅ Kantrybės',
        '✅ Savęs užuojautos (nesibaudyk už klaidas)',
        '',
        '**Tavo Pirmi Žingsniai (ŠIA SAVAITĘ):**',
        '',
        '**1. Nusifotografuok**',
        'Dabar. Kaip esi. Be filtrų. Tai tavasis "Day 1". Po 3 mėnesių padėkosi sau.',
        '',
        '**2. Užsirašyk 3 Tikslus**',
        'Ne tik "numesti 10kg". Bet:',
        '• "Jaustis energinga visą dieną"',
        '• "Treniruotis 3x/savaitę ir mėgautis"',
        '• "Laisva santykiu su maistu"',
        '',
        '**3. Pradėk Nuo 1 Pokyčio**',
        'Ne viską iškart. Pasirink VIENĄ:',
        '• Valgyk pusryčius su baltymais kasdien',
        '• Vaikščiok 10k žingsnių',
        '• Miegok 7h+',
        '• Treniruokis 3x/savaitę',
        '',
        'Po 2 savaičių - pridėk kitą.',
        '',
        '**4. Rask Palaikymą**',
        'Draugę, partnerę, trenerę, bendruomenę. NESI VIENA.',
        '',
        '**Nori Keliauti Su Manimi?**',
        '',
        'Renata Ladies - tai ne tik treniruočių programos. Tai BENDRUOMENĖ moterų, kurios palaiko viena kitą transformacijose.',
        '',
        'Mūsų programose gausi:',
        '• Treniruočių ir mitybos planus',
        '• Asmeninį palaikymą',
        '• Prieigą prie privačios FB grupės (100+ moterų kelionėje!)',
        '• Savaitiniai check-ins',
        '• Accountability',
        '**[Prisijunk prie bendruomenės →](/programos)**',
        '',
        'Ar nori 1-on-1 coaching su manimi?',
        '**[Rezervuoti konsultaciją →](/konsultacijos)**',
        '',
        '**P.S.** Po metų būsi vienais metais vyresnė bet kuriuo atveju. Klausimas tik - ar būsi vienais metais vyresnė IR transformavusi? Ar vienais metais vyresnė ir vis dar galvojanti "kada aš pradėsiu"?',
        '',
        'Pradėk dabar. Tavo ateities AŠ padėkos. ❤️💪✨'
      ]
    },
    seo: {
      metaTitle: 'Tikra Transformacijos Istorija: -10kg Per 6 Mėn | Renata Ladies',
      metaDescription: 'Mano asmeninė kelionė kaip numečiau 10kg ir atradau stiprumą. Be filtrų - klaidos, iššūkiai, rezultatai ir pamokos.',
      keywords: ['transformacijos istorija', 'kaip numesti 10kg', 'svorio metimas istorija', 'fitness transformacija', 'moters transformacija', 'motyvacija']
    }
  },
  {
    id: '10',
    slug: 'hormonai-ir-svoris-moterims',
    title: 'Hormonai ir Svoris: Kodėl Moterims Mesti Svorį Sunkiau (Ir Ką Daryti)',
    excerpt: 'Kodėl ta pati dieta vyrui veikia, o tau - ne? Viską lemia hormonai. Ekspertės gidas kaip dirbti SU hormonais, ne prieš.',
    category: 'Gyvenimo būdas',
    author: 'Renata Marcinkutė',
    publishedAt: '2025-08-05',
    readTime: '16 min',
    thumbnail: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=800&h=600&fit=crop&q=80',
    content: {
      attention: [
        'Tavo vyras/draugas pradeda dietą. Po 2 savaičių -5 kg. Tu darai TĄ PAČIĄ dietą, treniruojiesi net daugiau. Rezultatas? -1 kg. Arba svoris net pakilo.',
        'Kodėl taip? Vienas žodis: HORMONAI.',
      'Moterų hormoninė sistema yra DAUG sudėtingesnė nei vyrų. Estrogenas, progesteronas, testosteronas, kortizolis, insulinas, leptinas, grelinas – visi jie daro įtaką, kaip tavo kūnas laiko/meta svorį.',
        'Šis straipsnis - tavo vadovas kaip suprasti savo hormonus ir dirbti SU jais, ne prieš, optimaliam svorio metimui.'
      ],
      interest: [
        '**SVARBU: Aš nesu gydytoja. Jei įtari hormoninį disbalansą - kreipkis į endokrinologą ir darykite kraujo tyrimus!**',
        '',
        '**PAGRINDINIAI HORMONAI, VEIKIANTYS SVORĮ:**',
        '',
        '**1. ESTROGENAS (Moteriškas Hormonas)**',
        '',
        '**Kas tai:** Pagrindinis moterų hormonas, gaminamas kiaušidėse.',
        '',
        '**Kaip veikia svorį:**',
        '• **Optimalus lygis:** Padeda reguliuoti metabolizmą, paskirsto riebalus "moteriškai" (klubai/sėdmenys)',
        '• **Per didelis:** Vandens sulaikymas, pilvo riebalai, sunkumas mesti svorį',
        '• **Per mažas:** Lėtas metabolizmas, raumenų masės praradimas, pilvo riebalai',
        '',
      '**Ženklai, kad gali būti estrogeno disbalansas:**',
      '• Nereguliarios mėnesinės',
        '• PMS simptomai (nuotaikų svyravimai, išpūtimas)',
      '• Užsispyręs svoris pilvo srityje',
        '• Sunkumai miegoti',
        '',
        '**Ką daryti:**',
      '✅ Valgyk skaidulas (padeda eliminuoti perteklinį estrogeną)',
      '✅ Sumažink alkoholį (kepenys metabolizuoja estrogeną)',
        '✅ Valgyk kryžmažiedžių daržoves (brokoliai, kopūstai - DIM)',
      '✅ Sveiki riebalai (hormonų gamybai)',
      '❌ Venk plastikų su BPA (estrogenų imitatoriai)',
        '',
      '**2. PROGESTERONAS (Balanso Hormonas)**',
        '',
        '**Kas tai:** "Nėštumo hormonas", balansuoja estrogeną.',
        '',
        '**Kaip veikia svorį:**',
        '• Padeda reguliuoti skysčius',
        '• Gerina miegą (o miegas = svorio metimas!)',
        '• Mažina PMS simptomus',
        '',
      '**Per mažas progesteronas:**',
        '• Vandens sulaikymas',
        '• Saldumynų troškimas (ypač prieš mėnesines)',
        '• Nemiga',
        '• Nerimas',
        '',
        '**Ką daryti:**',
        '✅ Mažinti stresą (meditacija, yoga)',
        '✅ Magnis (300-400mg/dieną)',
        '✅ B6 vitaminas',
        '✅ Pakankamai miego (7-8h)',
        '',
        '**3. TESTOSTERONAS (Taip, Moterys Irgi Turi!)**',
        '',
        '**Kas tai:** Moterys turi 10-20x mažiau nei vyrai, bet vis tiek svarbus.',
        '',
        '**Kaip veikia svorį:**',
        '• Padeda statyti raumenis',
        '• Didina metabolizmą',
        '• Gerina libido',
        '• Energijos lygis',
        '',
        '**Per mažas testosteronas:**',
        '• Sunkumai statyti/palaikyti raumenis',
        '• Nuovargis',
        '• Mažas libido',
        '• Depresija',
        '',
        '**Ką daryti:**',
        '✅ JĖGOS TRENIRUOTĖS (didina testosteroną!)',
        '✅ Cinkas (15-30mg/dieną)',
        '✅ Sveiki riebalai (avokadas, riešutai)',
        '✅ Pakankamai baltymų',
        '❌ Vengį per didelio kardio (sumažina testosteroną)',
        '',
      '**4. KORTIZOLIS (Streso Hormonas)**',
        '',
        '**Kas tai:** "Fight or flight" hormonas, gaminamas antinksčiuose.',
        '',
      '**Įprastai:** Kortizolis padeda pabusti ryte ir suteikia energijos ūmaus streso metu.',
      '**Problema:** Lėtinis stresas = nuolat pakilęs kortizolis.',
        '',
      '**Per didelis kortizolis:**',
        '• Pilvo riebalai (ypač aplink vidurius)',
        '• Saldumynų troškimas',
        '• Nemiga',
        '• Nuolatinis nuovargis (bet "wired")',
        '• Sumažėję kiti hormonai',
        '',
        '**Ką daryti:**',
        '✅ STRESO VALDYMAS (meditacija, kvėpavimo pratimai)',
        '✅ Pakankamai miego (7-8h)',
        '✅ Adaptogenai (ashwagandha, rhodiola)',
        '✅ Mažiau kofeino (jei stresui)',
        '✅ Yoga, gamta, hobiai',
      '❌ Venk per agresyvių dietų (didina kortizolį)',
      '❌ Venk per daug treniruočių (overtraining = stresas)',
        '',
        '**5. INSULINAS (Cukraus Reguliavimo Hormonas)**',
        '',
        '**Kas tai:** Perneša cukrų iš kraujo į ląsteles.',
        '',
      '**Įprastai:** Valgai angliavandenius → insulinas pakyla → cukrus patenka į ląsteles.',
      '**Problema:** Insulino rezistencija = kūnas nereaguoja į insuliną → pakilęs cukraus kiekis kraujyje → riebalų kaupimas.',
        '',
      'Insulino rezistencijos ženklai:',
      '• Užsispyrę pilvo riebalai',
      '• Nuolatinis alkis (net pavalgius)',
      '• Energijos kritimas po valgymo',
        '• PCOS (policistinių kiaušidžių sindromas)',
        '• Tamsi oda ant kaklo/pažastų (acanthosis nigricans)',
        '',
        '**Ką daryti:**',
        '✅ Mažink rafinuotus angliavandenius/cukrų',
        '✅ Valgyk skaidulas (lėtina cukraus absorbciją)',
        '✅ Baltymai kiekviename valgyje',
        '✅ Intermittent fasting (jei tinka tau)',
        '✅ Jėgos treniruotės (gerina insulino jautrumą)',
      '✅ Chromas, berberinas (papildai – su gydytojo žinia)',
        '',
        '**6. LEPTINAS & GRELINAS (Alkio Hormonai)**',
        '',
        '**Leptinas:** "Sočių hormonas" - sako smegenims "sotus, sustok valgyti".',
        '**Grelinas:** "Alkio hormonas" - sako "alkanas, valgyk".',
        '',
      '**Problema:**',
        '• **Leptino rezistencija:** Kūnas negirdi "sotus" signalo → valgai daugiau.',
        '• **Pakilęs grelinas:** Nuolatinis alkio jausmas.',
        '',
        '**Kas kelia grelino:**',
        '• Miego stoka',
        '• Agresyvios dietos (per didelis kalorijų deficitas)',
        '• Stresas',
        '',
        '**Ką daryti:**',
        '✅ MIEGAS (7-8h - kritiškai svarbu!)',
        '✅ Pakankamas proteinas (gerina leptino jautrumą)',
        '✅ Ne per didelis kalorijų deficitas (maks -500 kcal)',
        '✅ Omega-3',
        '✅ Reguliarūs valgiai (ne labai reti)',
        '',
        '**MĖNESINIS CIKLAS IR SVORIS:**',
        '',
        'Moterų hormonai keičiasi per 28 dienų ciklą. Tai veikia VISKĄ: energiją, alkį, metabolizmą.',
        '',
        '**FAZĖ 1: Folikulinė (Dieną 1-14) - ESTROGENAS KYLA**',
        '**Kaip jaučiesi:** Daug energijos, gera nuotaika, mažesnis alkis.',
        '**Treniruotės:** IDEALUS laikas jėgos treniruotėms, HIIT, sunkioms treniruotėms.',
        '**Mityba:** Kūnas geriau tvarkosi su angliavandeniais.',
        '',
        '**FAZĖ 2: Ovuliacija (Dieną ~14) - PEAK**',
        '**Kaip jaučiesi:** Maksimali energija, jėga, libido.',
        '**Treniruotės:** Go hard! Geriausias laikas PR (personal record).',
        '',
      '**FAZĖ 3: Liuteinė (Dieną 15-28) - PROGESTERONAS KYLA**',
        '**Kaip jaučiesi:** Energija mažėja, alkis didėja, nuotaika svyruoja.',
        '**Treniruotės:** Lengvesnės treniruotės, yoga, LISS. Klausyk kūno.',
      '**Mityba:** Troškimas angliavandenių – normalu. Fokusas į sudėtingus angliavandenius + baltymus.',
        '',
        '**FAZĖ 4: Mėnesinės (Dieną 1-5) - VISI HORMONAI ŽEMI**',
        '**Kaip jaučiesi:** Nuovargis, skausmas, išpūtimas.',
        '**Treniruotės:** Jei jaučiesi gerai - lengvas jėga arba kardio. Jei blogai - poilsis/tempimas.',
        '**Mityba:** Geležis (prarandi per kraujavimą), magnis (skausmui), skaidulos (išpūtimui).'
      ],
      desire: [
        '**KAIP OPTIMIZUOTI MITYBĄ/TRENIRUOTES PAGAL HORMONUS:**',
        '',
        '**SAVAITĖS 1-2 (Folikulinė/Ovuliacija):**',
        '**Treniruotės:**',
        '• 4-5x jėgos treniruotės',
        '• HIIT 2x',
        '• Didink svorius, bandom PR',
        '',
        '**Mityba:**',
        '• Daugiau angliavandenių (kūnas geriau metabolizuoja)',
        '• Baltymai: 1.8-2g/kg',
        '• Gali bandyti kalorijų deficitą (lengviau toleruoti)',
        '',
        '**SAVAITĖS 3-4 (Liuteinė/Mėnesinės):**',
        '**Treniruotės:**',
        '• 3x jėgos (lengviau)',
        '• LISS kardio',
        '• Yoga, tempimas',
        '• Klausyk kūno - jei reikia poilsio, duok!',
        '',
        '**Mityba:**',
        '• Daugiau sveikų riebalų',
        '• Magnis (skausmui, nuotaikai)',
        '• Leisk sau daugiau kalorijų (ypač prieš mėnesines)',
        '• Tamsusis šokoladas geležiui + "sielos maistui" 😊',
        '',
        '**KADA KREIPTIS Į GYDYTOJĄ:**',
        '',
                        '🚨 **Būtinai patikrink hormonus, jei:**',
        '• Nereguliarių/labai sunkių mėnesinių',
        '• Svoris kyla net su griežta dieta',
        '• Nuolatinis nuovargis',
        '• Plaukų slinkimas',
        '• Labai mažas libido',
        '• Nerimas/depresija',
        '• Nemiga',
        '',
                        '**Kokie tyrimai:**',
                        '• TSH, T3, T4 (skydliaukė – labai veikia metabolizmą!)',
        '• Estrogenas, progesteranas, testosteronas',
                        '• Kortizolis (ryte)',
        '• Insulinas, gliukozė',
        '• DHEA-S',
        '',
        '**DAŽNIAUSIOS HORMONINĖS PROBLEMOS:**',
        '',
        '**PCOS (Policistinių Kiaušidžių Sindromas):**',
        '• ~10% moterų',
        '• Insulino rezistencija, pakilęs testosteronas',
                        '• Sunkumai mesti svorį, plaukuotumas, nereguliarios mėnesinės',
                        '**Sprendimas:** Mažo GI dieta, inozitolis, metforminas (su gydytoju)',
        '',
        '**Hipotiroidizmas (Lėta Skydliaukė):**',
        '• Lėtas metabolizmas, nuovargis, šaltumas, plaukų slinkimas',
                        '**Sprendimas:** Levotiroksinas (su gydytoju), selenas, jodas',
        '',
                        '**Antinksčių nuovargis:**',
                        '• Lėtinis stresas → išsekę antinksčiai → mažas kortizolis',
        '• "Tired but wired"',
        '**Sprendimas:** Poilsis, adaptogenai, streso valdymas',
        '',
        '**TIKROS MOTERŲ ISTORIJOS:**',
        '',
                        '**Ieva, 31m:** "Metai bandžiau mesti svorį – nieko neveikė. Pasitikrinus hormonus – PCOS. Pradėjau mažo GI dietą + inozitolį + jėgos treniruotes. Per 6 mėn –8 kg ir reguliarios mėnesinės pirmą kartą per 5 metus!"',
        '',
                        '**Laura, 35m:** "Nuolatinis nuovargis, svoris kilo net valgant 1400 kcal. Paaiškėjo hipotiroidizmas. Pradėjau levotiroksiną su gydytoju + seleną. Energija grįžo, svoris pradėjo kristi."'
      ],
      action: [
        '**Tavo "Hormonal Health" Action Plan:**',
        '',
        '**☑ ŠIĄ SAVAITĘ:**',
        '',
        '**1. Sekti Ciklą**',
        'Atsisiųsk aplikaciją (Flo, Clue). Sekti mėnesines, energijos lygius, nuotaiką, alkį.',
        '',
        '**2. Kraujo Tyrimai**',
        'Užsiregistruok pas gydytoją. Paprašyk bent: TSH, estrogenas, progesteranas, insulinas.',
        '',
        '**3. Miego Optimizacija**',
        'Tikslas: 7-8h. Režimas: miegoti/keltis tuo pačiu laiku.',
        '',
        '**4. Streso Auditas**',
        'Užsirašyk: Kas kelia stresą? Kaip galiu sumažinti?',
        '',
        '**☑ KITAS MĖNUO:**',
        '',
      '**5. Treniruokis pagal ciklą**',
        'Savaitės 1-2: sunkiai. Savaitės 3-4: lengvai. Stebėk skirtumą!',
        '',
        '**6. Mityba Hormonų Palaikymui**',
        '• Baltymai kiekviename valgyje',
        '• Sveiki riebalai kasdien',
        '• Skaidulos 25-30g/dieną',
      '• Mažink perdirbtą maistą/cukrų',
        '',
        '**7. Papildai (Su Gydytojo Žinia)**',
        '• Magnis (300-400mg)',
        '• Omega-3 (1000-2000mg EPA+DHA)',
        '• D3 vitaminas (2000-4000 IU)',
        '',
        '**Nori Pagalbos Balansuoti Hormonus Natūraliai?**',
        '',
        'Mūsų "Hormonal Balance" programoje:',
        '• Personalizuotas mitybos planas hormonų balansui',
        '• Treniruočių programa pritaikyta ciklui',
        '• Streso valdymo technikos',
        '• Papildų rekomendacijos',
        '• Mėnesinis check-in ir korektūros',
        '**[Sužinok apie programą →](/konsultacijos)**',
        '',
        'Ar nori konsultacijos dėl hormoninio disbalanso?',
        '**[Rezervuoti konsultaciją →](/konsultacijos)**',
        '',
                        '**P.S.** Jei metais bandai mesti svorį ir niekas neveikia – problema nebūtinai tavo valios stoka. Problema gali būti hormonai. Patikrink juos. Dirbk SU savo kūnu, ne prieš jį. Kai hormonai balansuojasi – svoris krenta LENGVAI. Tu nesi "lazy" ar "silpna" – tiesiog reikia suprasti, ką tavo kūnas bando tau pasakyti. 🧬💕'
      ]
    },
    seo: {
      metaTitle: 'Hormonai ir Svoris Moterims 2025 (Pilnas Gidas)',
                  metaDescription: 'Kodėl moterims sunkiau mesti svorį? Viską lemia hormonai. Sužinok kaip estrogenas, kortizolis, insulinas veikia svorį ir ką daryti.',
                  keywords: ['hormonai ir svoris', 'moterų hormonai', 'kodėl negaliu numesti svorio', 'estrogenas', 'kortizolis', 'PCOS', 'hormoninis balansas']
    }
  }
]

export function getBlogPostBySlug(slug: string): BlogPost | undefined {
  return BLOG_POSTS.find(post => post.slug === slug)
}

export function getBlogPostsByCategory(category: string): BlogPost[] {
  return BLOG_POSTS.filter(post => post.category === category)
}

export const BLOG_CATEGORIES = [
  'Visos',
  'Treniruotės',
  'Mityba',
  'Motyvacija',
  'Receptai',
  'Gyvenimo būdas'
]
